# Generated by Django 3.0.8 on 2020-07-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vg', '0001_squashed_0002_measurement_fragment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='cal_base_file_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_1', to='vg.Measurement', verbose_name='Basefile 1 used for this cal.'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_base_file_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_2', to='vg.Measurement', verbose_name='Basefile 2 used for this cal.'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_base_file_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_3', to='vg.Measurement', verbose_name='Basefile 3 used for this cal.'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='cal_base_file_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_4', to='vg.Measurement', verbose_name='Basefile 4 used for this cal.'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='calibration_plot',
            field=models.FileField(blank=True, upload_to='vg/calibrations/'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='formula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calibration formula for copy-pasting'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='logoutput',
            field=models.TextField(blank=True, verbose_name='Log output of fitlib'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='vg/techjournal/'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='background_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Background Pressure in IS (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='channeltron',
            field=models.FloatField(default=2.3, verbose_name='Channeltron (kV)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='datafile',
            field=models.FileField(max_length=400, upload_to='vg/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='electron_energy',
            field=models.FloatField(blank=True, null=True, verbose_name='Electron Energy (for MS)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='polarity',
            field=models.CharField(choices=[('NEG', 'Negative'), ('POS', 'Positive')], default='NEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressure_analyzer',
            field=models.CharField(default='1e-8', max_length=7, verbose_name='Pressure Analyzer (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressure_ionblock',
            field=models.CharField(default='1e-6', max_length=7, verbose_name='Pressure Ion Block (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='scantype',
            field=models.CharField(choices=[('ES', 'Energyscan'), ('MS', 'Massscan'), ('MIKE', 'MIKE-Scan'), ('CID', 'CID-Scan')], default='ES', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='x_deflect',
            field=models.FloatField(verbose_name='Y-Deflect'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='y_focus',
            field=models.FloatField(verbose_name='Y-Focus'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='z_deflect',
            field=models.FloatField(verbose_name='Z-Deflect'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='z_deflect_1',
            field=models.FloatField(verbose_name='Z-Deflect 1'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='z_deflect_2',
            field=models.FloatField(verbose_name='Z-Deflect 2'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='z_focus_1',
            field=models.FloatField(verbose_name='Z-Focus 1'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='z_focus_2',
            field=models.FloatField(verbose_name='Z-Focus 2'),
        ),
    ]
