# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('attachment', models.FileField(blank=True, default=b'', upload_to=b'snowball/techjournal/')),
                ('written_notes', models.ImageField(blank=True, upload_to=b'snowball/techjournal/notes/')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('datafile', models.FileField(max_length=400, upload_to=b'snowball/%Y/%m/%d/%H/%M/%S/')),
            ],
            options={
                'ordering': ['-starttime'],
                'get_latest_by': 'starttime',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Turbopump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurbopumpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowball.Turbopump')),
            ],
            options={
                'verbose_name_plural': 'Turbopump Status',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowball.Operator'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowball.Operator'),
        ),
    ]
