# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball', '0003_auto_20161207_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='ec',
            field=models.FloatField(default=100.0, verbose_name=b'Electron Current'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ee',
            field=models.FloatField(default=70.0, verbose_name=b'Electron Energy'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='he_pres',
            field=models.FloatField(default=20.0, verbose_name=b'He pressure'),
        ),
    ]
