# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball', '0004_auto_20171002_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='text',
            field=models.TextField(default=b'None', max_length=1500, verbose_name=b'Comment'),
        ),
    ]
