version: '3.8'

services:

    nginx:
        image: labbooks-nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "8012:80"
        volumes:
            - /media/netshare/Temp/labbooks:/src/media:ro
        depends_on:
            - django

    django:
        image: labbooks-django
        build:
            context: .
            dockerfile: django.Dockerfile
        restart: always
        volumes:
            - /media/netshare/Temp/labbooks:/src/media
            - /media/netshare/Experiments/Toffy2/Measurements/RAW-TOFWERK-Data:/src/media_toffy2_tofwerk_data:ro
            - /media/netshare/Experiments/SurfTOF/Measurements/rawDATA:/src/media_surftof_data:ro
        expose:
            - "8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: P5VINNAZVh2W6luqSvDQOTCQA5NqLgb5n5KMPM3F3rgfo0cjOi5kaDs3n0sfsn
            POSTGRES_USER: labbooks
            POSTGRES_DB: labbooks

        volumes:
            - postgres-data:/var/lib/postgresql/data/

volumes:
    postgres-data:
