version: '3.8'

services:

    nginx:
        image: labbooks-nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "8012:80"
        volumes:
            - ./media:/src/media:ro
        depends_on:
            - django

    django:
        image: labbooks-django
        build:
            context: .
            dockerfile: django.Dockerfile
        restart: always
        volumes:
            - ./media:/src/media
        expose:
            - "8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: P5VINNAZVh2W6luqSvDQOTCQA5NqLgb5n5KMPM3F3rgfo0cjOi5kaDs3n0sfsn
            POSTGRES_USER: labbooks
            POSTGRES_DB: labbooks

        volumes:
            - postgres-data:/var/lib/postgresql/data/

volumes:
    # media:    # todo: add cifs mount
    postgres-data:
