version: '3.8'

services:

    nginx:
        image: labbooks-nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "8012:80"
        volumes:
            - media:/src/media:ro
        depends_on:
            - django

    django:
        image: labbooks-django
        build:
            context: .
            dockerfile: django.Dockerfile
        restart: always
        volumes:
            - media:/src/media:ro
            - media-toffy2-tofwerk-data:/src/media_toffy2_tofwerk_data:ro
            - media-surftof-data:/src/media_surftof_data:ro
        expose:
            - "8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: P5VINNAZVh2W6luqSvDQOTCQA5NqLgb5n5KMPM3F3rgfo0cjOi5kaDs3n0sfsn
            POSTGRES_USER: labbooks
            POSTGRES_DB: labbooks

        volumes:
            - postgres-data:/var/lib/postgresql/data/

volumes:
    postgres-data:
    media:
        driver: local
        driver_opts:
            type: cifs
            device: "//${NETSHARE_DOMAIN}/${NETSHARE_PATH}"
            o: "addr=${NETSHARE_DOMAIN},username=${NETSHARE_USER},password=${NETSHARE_PW},domain=${NETSHARE_AD_DOMAIN},file_mode=0775,dir_mode=0775"

    media-toffy2-tofwerk-data:
        driver: local
        driver_opts:
            type: cifs
            device: "//${NETSHARE_DOMAIN}/${NETSHARE_PATH_TOFFY2_TOFWERK_DATA}"
            o: "addr=${NETSHARE_DOMAIN},username=${NETSHARE_USER},password=${NETSHARE_PW},domain=${NETSHARE_AD_DOMAIN},file_mode=0775,dir_mode=0775"

    media-surftof-data:
        driver: local
        driver_opts:
            type: cifs
            device: "//${NETSHARE_DOMAIN}/${NETSHARE_PATH_SURFTOF_DATA}"
            o: "addr=${NETSHARE_DOMAIN},username=${NETSHARE_USER},password=${NETSHARE_PW},domain=${NETSHARE_AD_DOMAIN},file_mode=0775,dir_mode=0775"
