version: '3.8'

services:

    nginx:
        image: labbooks-nginx
        build:
            context: .
            dockerfile: nginx.Dockerfile
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./test_volume:/src/media:ro
        depends_on:
            - django

    django:
        image: labbooks-django
        build:
            context: .
            dockerfile: django.Dockerfile
        restart: always
        volumes:
            - ./test_volume:/src/media
            - ./test_volume:/src/media_toffy2_tofwerk_data:ro
            - ./test_volume:/src/media_surftof_data:ro
        expose:
            - "8000"
        depends_on:
            - postgres

    postgres:
        image: postgres:15-alpine
        restart: always
        environment:

            POSTGRES_USER: labbooks
            POSTGRES_DB: labbooks

        volumes:
            - postgres-data:/var/lib/postgresql/data/

volumes:
    postgres-data:
