# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cheminventory', '0006_auto_20160322_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('persons', models.ManyToManyField(to='cheminventory.Person')),
            ],
        ),
    ]
