# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0004_vacuumstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuumstatus',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
