# Generated by Django 3.2.12 on 2022-08-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0002_delete_measurementdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sputter_method',
            field=models.CharField(blank=True, choices=[('magnetronTi', 'Magnetron'), ('magnetronAu', 'Magnetron Gold'), ('snowball', 'Snowball'), ('toffy', 'Toffy'), ('hollowCathode', 'Hollow Cathode')], default='magnetronTi', max_length=20, null=True),
        ),
    ]
