# Generated by Django 3.2.12 on 2022-08-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0006_remove_measurement_sputter_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sputter_method_link',
            new_name='sputter_method',
        ),
    ]
