# Generated by Django 3.2.16 on 2023-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0007_rename_sputter_method_link_measurement_sputter_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='nid_file',
            field=models.FileField(blank=True, upload_to='nanoparticles/nidfiles/'),
        ),
    ]
