# Generated by Django 3.1.1 on 2020-09-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toffy2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluated_by', to='toffy2.operator'),
        ),
    ]
