# Generated by Django 3.0.8 on 2020-07-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('moses', '0001_initial'), ('moses', '0002_file_name'), ('moses', '0003_auto_20200321_0944')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=b'moses')),
                ('name', models.CharField(default='Test', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('files', models.ManyToManyField(blank=True, related_name='target_image', to='moses.File')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200)),
                ('step_size', models.IntegerField(help_text=b'Unit: micro meter')),
                ('evaluation_file', models.ManyToManyField(blank=True, help_text=b'Zip evaluation files', related_name='evaluation_file', to='moses.File')),
                ('image', models.ManyToManyField(blank=True, related_name='image', to='moses.File', verbose_name=b'Evaluated Image')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moses.Target')),
            ],
        ),
    ]
