# Generated by Django 3.0.8 on 2020-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0001_squashed_0003_auto_20200321_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='moses'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='evaluation_file',
            field=models.ManyToManyField(blank=True, help_text='Zip evaluation files', related_name='evaluation_file', to='moses.File'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='image', to='moses.File', verbose_name='Evaluated Image'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='step_size',
            field=models.IntegerField(help_text='Unit: micro meter'),
        ),
    ]
