# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-21 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moses', '0002_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='time',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='x_max',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='x_min',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='y_max',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='y_min',
        ),
    ]
