# Generated by Django 3.0.8 on 2020-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsetube', '0001_squashed_0003_auto_20200617_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data_file',
            field=models.FileField(blank=True, upload_to='pulsetube/dataFiles/'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='he_pres',
            field=models.FloatField(verbose_name='He stagnation pressure'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='he_temp',
            field=models.FloatField(verbose_name='He temperature'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ion_source_electron_energy',
            field=models.FloatField(verbose_name='Electron Energy [V]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ion_source_fc_current',
            field=models.FloatField(verbose_name='FC Current [uA]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ion_source_filament_current',
            field=models.FloatField(verbose_name='Filament Current [A]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='polarity',
            field=models.CharField(choices=[('pos', 'positive'), ('neg', 'negative')], max_length=3),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('mass', 'Mass scan'), ('energy', 'Energy scan'), ('current', 'Current scan'), ('temperature', 'Temperature scan')], max_length=20, null=True),
        ),
    ]
