# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0008_unpopulate_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='substance_links',
            new_name='substance',
        ),
    ]
