# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0010_auto_20160906_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='substance_comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
