# Generated by Django 3.0.8 on 2020-07-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0002_auto_20200703_1603'),
        ('wippi', '0011_auto_20160906_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration',
            name='cal_base_file_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file', to='wippi.Measurement', verbose_name='Basefile used for this cal.'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='calibration_plot',
            field=models.FileField(blank=True, upload_to='wippi/calibrations/'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='formula',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calibration formula for copy-pasting'),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='logoutput',
            field=models.TextField(blank=True, verbose_name='Log output of fitlib'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='wippi/techjournal/'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wippi.Operator'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='background_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Background Pressure in MC (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='base_pressure',
            field=models.CharField(blank=True, max_length=7, verbose_name='Base Pressure Cluster Source (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='channeltron_1',
            field=models.FloatField(blank=True, default=5.8, null=True, verbose_name='Channeltron 1'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='channeltron_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Channeltron 2'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_current_xy',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Current XY'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_current_xz',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Current XZ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_current_yz',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Current YZ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_voltage_xy',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Voltage XY'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_voltage_xz',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Voltage XZ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='coil_voltage_yz',
            field=models.FloatField(blank=True, null=True, verbose_name='Coil Voltage YZ'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='datafile',
            field=models.FileField(max_length=400, upload_to='wippi/%Y/%m/%d/%H/%M/%S/'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='electron_energy',
            field=models.FloatField(blank=True, null=True, verbose_name='Electron Energy (for MS)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='mass_resolution',
            field=models.FloatField(blank=True, default=25, null=True, verbose_name='Mass Resolution (Quadrupole)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='nozzle',
            field=models.FloatField(blank=True, default=12, null=True, verbose_name='Nozzle Temperature'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wippi.Operator'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='polarity',
            field=models.CharField(choices=[('NEG', 'Negative'), ('POS', 'Positive')], default='NEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressure_cs',
            field=models.CharField(blank=True, max_length=7, verbose_name='Pressure Cluster Source (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressure_monochromator',
            field=models.CharField(default='2e-6', max_length=7, verbose_name='Pressure MC (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pressure_pickup',
            field=models.CharField(blank=True, max_length=7, verbose_name='Pressure Pickup (mbar)'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='qmh',
            field=models.CharField(blank=True, max_length=5, verbose_name='QMH'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='scantype',
            field=models.CharField(choices=[('ES', 'Energyscan'), ('MS', 'Massscan')], default='ES', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='substance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cheminventory.Chemical'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ue',
            field=models.FloatField(blank=True, null=True, verbose_name='Ue'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='ue_fine',
            field=models.FloatField(blank=True, null=True, verbose_name='Ue fine'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uex_mitte',
            field=models.FloatField(blank=True, null=True, verbose_name='Uex Mitte'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uhk_mitte',
            field=models.FloatField(blank=True, null=True, verbose_name='UHK Mitte'),
        ),
    ]
