# Generated by Django 3.0.8 on 2020-07-03 14:03

import cheminventory.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0001_squashed_0008_auto_20190326_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='cas',
            field=models.CharField(blank=True, max_length=12, validators=[cheminventory.validations.validate_CAS], verbose_name='CAS-Number'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='chemical_formula',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, validators=[cheminventory.validations.validate_chemical_formula], verbose_name='Chemical Formula'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='csid',
            field=models.IntegerField(blank=True, null=True, verbose_name='CSID'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='environmentally_damaging',
            field=models.BooleanField(verbose_name='Environ. dam.'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='inchi',
            field=models.CharField(blank=True, db_index=True, max_length=700, verbose_name='InChI'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='inchikey',
            field=models.CharField(blank=True, db_index=True, max_length=27, verbose_name='InChI-Key'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='name',
            field=models.CharField(db_index=True, max_length=100, validators=[cheminventory.validations.validate_name], verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='no_chemspider_sync',
            field=models.BooleanField(default=False, verbose_name='Do not sync with chemspider service'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='state_of_matter',
            field=models.CharField(choices=[('FLUID', 'Fluid'), ('GAS', 'Gas Phase'), ('SOLID', 'Solid')], default='FLUID', max_length=5),
        ),
        migrations.AlterField(
            model_name='chemicalinstance',
            name='cylinder_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Number of gas cylinder in wiki'),
        ),
        migrations.AlterField(
            model_name='chemicalinstance',
            name='group',
            field=models.CharField(choices=[('DENIFL', 'Denifl'), ('SCHEIER', 'Scheier')], default='DENIFL', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='gascylinder',
            name='cylinder_number',
            field=models.IntegerField(unique=True, verbose_name='Number of gas cylinder'),
        ),
        migrations.AlterField(
            model_name='gascylinder',
            name='group',
            field=models.CharField(choices=[('DENIFL', 'Denifl'), ('SCHEIER', 'Scheier')], default='SCHEIER', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='suitable_for',
            field=models.CharField(choices=[('FLUID', 'Fluid'), ('GAS', 'Gas Phase'), ('SOLID', 'Solid')], max_length=5),
        ),
    ]
