# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0005_gascylinder_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalinstance',
            name='cylinder_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Number of gas cylinder in wiki'),
        ),
    ]
