# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0006_auto_20160322_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalinstance',
            name='item_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
