# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0007_chemicalinstance_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
