# Generated by Django 3.2.12 on 2022-07-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffy2', '0005_measurement_data_file_path_h5'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='rating',
            field=models.IntegerField(choices=[(1, 'good'), (2, 'neutral'), (3, 'bad')], default=2),
        ),
    ]
