# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaugetype',
            name='modus',
            field=models.CharField(choices=[(b'PIR', b'Pirani'), (b'FULL', b'Full Range'), (b'COLD', b'Cold Cathode'), (b'UNKN', b'Unknown')], max_length=4),
        ),
    ]
