# Generated by Django 3.0.8 on 2020-07-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('labinventory', '0001_initial'), ('labinventory', '0002_auto_20190326_0947')]

    initial = True

    dependencies = [
        ('cheminventory', '0007_chemicalinstance_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('modus', models.CharField(choices=[(b'PIR', b'Pirani'), (b'FULL', b'Full Range'), (b'COLD', b'Cold Cathode'), (b'UNKN', b'Unknown')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PressureGauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.GaugeType')),
                ('usage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheminventory.UsageLocation')),
            ],
        ),
        migrations.CreateModel(
            name='PressureGaugeUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.PressureGauge')),
                ('usage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheminventory.UsageLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheminventory.Person')),
            ],
        ),
    ]
