# Generated by Django 3.0.8 on 2020-07-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GaugeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('PIR', 'Pirani'), ('FULL', 'Full Range'), ('COLD', 'Cold Cathode'), ('UNKN', 'Unknown')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PressureGauge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.GaugeType')),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('temp_sensor_1', models.FloatField(blank=True, null=True, verbose_name='Temperature Prevacuum Room')),
                ('temp_sensor_2', models.FloatField(blank=True, null=True, verbose_name='Temperature Big Lab Room')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=6)),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PressureGaugeUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('gauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.PressureGauge')),
                ('usage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.UsageLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.Person')),
            ],
        ),
        migrations.AddField(
            model_name='pressuregauge',
            name='usage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.UsageLocation'),
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('poweralarm', 'Power alarm'), ('tempalarm', 'Temperature alarm')], max_length=10)),
                ('persons', models.ManyToManyField(to='labinventory.Person')),
            ],
        ),
    ]
