# Generated by Django 3.2.9 on 2021-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='get_power_alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='get_temperature_alarm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.FloatField(blank=True, help_text='Use numbers only, i.e. 0043699123456789', null=True),
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
