# Generated by Django 3.0.8 on 2020-07-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0001_squashed_0002_auto_20190326_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('temp_sensor_1', models.FloatField(blank=True, null=True, verbose_name='Temperature Prevacuum Room')),
                ('temp_sensor_2', models.FloatField(blank=True, null=True, verbose_name='Temperature Big Lab Room')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=6)),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='gaugetype',
            name='modus',
        ),
        migrations.AddField(
            model_name='gaugetype',
            name='mode',
            field=models.CharField(choices=[('PIR', 'Pirani'), ('FULL', 'Full Range'), ('COLD', 'Cold Cathode'), ('UNKN', 'Unknown')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('poweralarm', 'Power alarm'), ('tempalarm', 'Temperature alarm')], max_length=10)),
                ('persons', models.ManyToManyField(to='labinventory.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='pressuregauge',
            name='usage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.UsageLocation'),
        ),
        migrations.AlterField(
            model_name='pressuregaugeusagerecord',
            name='usage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.UsageLocation'),
        ),
        migrations.AlterField(
            model_name='pressuregaugeusagerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labinventory.Person'),
        ),
    ]
