# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0002_auto_20190326_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('temp_sensor_1', models.FloatField(blank=True, null=True, verbose_name=b'Teperature Prevacuum Room')),
                ('temp_sensor_2', models.FloatField(blank=True, null=True, verbose_name=b'Teperature Big Lab Room')),
            ],
        ),
    ]
