# Generated by Django 3.2.12 on 2022-07-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0004_alter_person_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='get_power_alarm',
        ),
        migrations.RemoveField(
            model_name='person',
            name='get_temperature_alarm',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mobile',
        ),
    ]
