# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='base_pressure',
            field=models.CharField(blank=True, max_length=7, verbose_name=b'Base Pressure Cluster Source (mbar)'),
        ),
    ]
