# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0006_auto_20160322_1543'),
        ('wippi', '0004_measurement_nozzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='substance_links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cheminventory.Chemical'),
        ),
    ]
