# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 13:23
from __future__ import unicode_literals

from django.db import migrations, models

def populate_links(apps, schema_editor):
    Measurements = apps.get_model('wippi', 'Measurement')
    Chemicals = apps.get_model('cheminventory', 'Chemical')
    for m in Measurements.objects.all():
        chem = Chemicals.objects.filter(chemical_formula = m.substance)
        if len(chem) == 0:
            chem = Chemicals.objects.filter(name = m.substance)
            if len(chem) == 0:
                chem = Chemicals.objects.filter(name = 'Unknown')

        m.substance_links = chem[0]
        m.save()

def unpopulate_links(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0005_measurement_substance_links'),
    ]

    operations = [
        migrations.RunPython(populate_links, unpopulate_links),
    ]
