# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0006_create_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='substance',
            new_name='substance_comments',
        ),
    ]
