# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball', '0002_auto_20160428_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='endtime',
        ),
        migrations.AddField(
            model_name='measurement',
            name='he_temp',
            field=models.FloatField(default=9.5, verbose_name=b'He temp'),
        ),
    ]
