# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball', '0006_measurement_chan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='text',
            field=models.TextField(blank=True, max_length=1500, verbose_name=b'Comment'),
        ),
    ]
