# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball', '0008_measurement_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='ec_2',
            field=models.FloatField(default=100.0, verbose_name=b'Electron Current IS2'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ee_2',
            field=models.FloatField(default=70.0, verbose_name=b'Electron Energy IS2'),
        ),
    ]
