# Generated by Django 3.2.9 on 2021-12-07 12:58

from django.db import migrations, models
import labinventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('labinventory', '0003_alter_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, default='0', help_text='Allowed format: 0043699123456789, +43699123456789, 0699123456789', max_length=20, validators=[]),
            preserve_default=False,
        ),
    ]
