from django.urls import path
from clustof.models import Measurement, JournalEntry, Turbopump
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.contrib.flatpages import views as flatpageviews
import clustof.views

urlpatterns = [
    path('newmeasurement/',
         clustof.views.newmeasurement,
         name="clustof-newmeasurement"),
    path('view/',
         ListView.as_view(model=Measurement, template_name='clustof/measurement_list.html', paginate_by=100),
         name="clustof-view-measurements"),
    path('pumps/',
         ListView.as_view(model=Turbopump, template_name='clustof/pump_list.html'),
         name="clustof-view-pumps"),
    path('pumps/<int:pumpnumber>',
         clustof.views.pump,
         name="clustof-view-pump"),
    path('insight/<parameter1>/<parameter2>/',
         clustof.views.plot_parameters,
         name="clustof-insight-parameter1-parameter2"),
    path('insight/',
         lambda x: HttpResponseRedirect('extraction_1/extraction_2/'),
         name="clustof-insight"),
    path('insight/<parameter1>/',
         clustof.views.plot_parameters,
         name="clustof-insight-parameter1"),
    path('journal/',
         ListView.as_view(model=JournalEntry, template_name='clustof/journalentry_list.html'),
         name="clustof-view-journals"),
    path('journal/new/',
         clustof.views.newjournalentry,
         name="clustof-journal-new"),
    path('journal/<int:id>/',
         clustof.views.showjournalentry,
         name="clustof-view-journal"),
    path('',
         flatpageviews.flatpage, {'url': '/clustof/'},
         name='clustof-home'),
    path('export/<int:id>/',
         clustof.views.exportfile,
         name="clustof-exportfile"),
    path('export/<int:id>/filename',
         clustof.views.exportfilename,
         name="clustof-exportfilename"),
    path('json/<int:count>/',
         clustof.views.mjson,
         name="clustof-mjson"),
    path('csv/<int:count>/<int:offset>/',
         clustof.views.mcsv,
         name="clustof-mcsv-count-offset"),
    path('csv/<int:count>/',
         clustof.views.mcsv,
         name="clustof-mcsv-count"),
    path('csv/',
         clustof.views.mcsv,
         name="clustof-mcsv"),
    path('vacuumstatus/input/',
         clustof.views.readvacuumstatus,
         name="clustof-readvacuumstatus"),
    path('vacuumstatus/output/<int:after>/<int:before>/',
         clustof.views.writevacuumstatus,
         name="clustof-writevacuumstatus-after-before"),
    path('vacuumstatus/output/<int:after>/',
         clustof.views.writevacuumstatus,
         name="clustof-writevacuumstatus-after"),
    path('vacuumstatus/output/',
         clustof.views.writevacuumstatus,
         name="clustof-writevacuumstatus"),
    path('filetest/',
         clustof.views.filetest,
         name="clustof-filetest"),
    path('public/',
         clustof.views.PublicMeasurementList.as_view(),
         name="clustof-public-measurements"),
    path('public/<int:pk>/',
         clustof.views.PublicMeasurementDetailView.as_view(),
         name="clustof-public-measurement"),
    path('public/<int:pk>/export/',
         clustof.views.exportfile_public,
         name="clustof-public-exportfile"),
]
