# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-27 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('potential_type', models.CharField(choices=[(b'RG', b'Residual gas'), (b'SURF', b'Up to surface only'), (b'ALL', b'All'), (b'ELSE', b'Else. See description / comment')], default=b'ALL', max_length=4)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('spark_plug', models.FloatField(blank=True, null=True)),
                ('nozzle', models.FloatField(blank=True, null=True)),
                ('skimmer', models.FloatField(blank=True, null=True)),
                ('wien_in', models.FloatField(blank=True, null=True)),
                ('wien_out', models.FloatField(blank=True, null=True)),
                ('wien_e_top', models.FloatField(blank=True, null=True)),
                ('wien_e_bottom', models.FloatField(blank=True, null=True)),
                ('wien_magnet', models.FloatField(blank=True, null=True)),
                ('focus_1', models.FloatField(blank=True, null=True)),
                ('quad_ref', models.FloatField(blank=True, null=True)),
                ('quad_field_axis', models.FloatField(blank=True, null=True)),
                ('focus_2_inner', models.FloatField(blank=True, null=True)),
                ('focus_2_outer', models.FloatField(blank=True, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('focus_3_outer', models.FloatField(blank=True, null=True)),
                ('focus_3_inner', models.FloatField(blank=True, null=True)),
                ('ion_spacer', models.FloatField(blank=True, null=True)),
                ('extraction', models.FloatField(blank=True, null=True)),
                ('focus_4', models.FloatField(blank=True, null=True)),
                ('slit_disc', models.FloatField(blank=True, null=True)),
                ('tof_is_ref', models.FloatField(blank=True, null=True)),
                ('pusher', models.FloatField(blank=True, null=True)),
                ('tof_zero_level', models.FloatField(blank=True, null=True)),
                ('tof_drift_l1', models.FloatField(blank=True, null=True, verbose_name=b'TOF Drift and L1')),
                ('tof_l2', models.FloatField(blank=True, null=True, verbose_name=b'TOF L2')),
                ('tof_ll', models.FloatField(blank=True, null=True, verbose_name=b'TOF LL')),
                ('mcp', models.FloatField(blank=True, null=True, verbose_name=b'MCP')),
                ('comment', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
