# Generated by Django 3.0.8 on 2020-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0001_squashed_0016_auto_20200109_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsegAssignments',
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterField(
            model_name='countspermass',
            name='counts',
            field=models.FloatField(verbose_name='Normalized Counts'),
        ),
        migrations.AlterField(
            model_name='countspermass',
            name='mass',
            field=models.FloatField(help_text='Use only the integer masses here, except "half masses" (28.5m/z)'),
        ),
        migrations.AlterField(
            model_name='countspermass',
            name='molecule',
            field=models.CharField(blank=True, help_text='E.g. Be2D3. Only use this field, if you are sure, that the counts are not a combination of different molecules!', max_length=100, verbose_name='Molecular formula'),
        ),
        migrations.AlterField(
            model_name='gas',
            name='comment',
            field=models.TextField(blank=True, help_text='Add infos like gas bottle number, purity, reseller, ...', null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rating',
            field=models.IntegerField(choices=[(5, '5 - Science'), (4, '4 - Interesting'), (3, '3 - Normal'), (2, '2 - Not interesting'), (1, '1 - Trash')], default=3),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='tof_ions',
            field=models.CharField(choices=[('NEG', 'Negative'), ('POS', 'Positive')], default='POS', max_length=3),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='filament_tof_bottom_current',
            field=models.FloatField(blank=True, help_text='The current is produced by the filament top', null=True),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='mcp',
            field=models.FloatField(blank=True, null=True, verbose_name='MCP'),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='slit_disc_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='Slit disc angle in degrees'),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='surface_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface angle in degrees'),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='tof_drift_l1',
            field=models.FloatField(blank=True, null=True, verbose_name='TOF Drift and L1'),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='tof_l2',
            field=models.FloatField(blank=True, null=True, verbose_name='TOF L2'),
        ),
        migrations.AlterField(
            model_name='potentialsettings',
            name='tof_ll',
            field=models.FloatField(blank=True, null=True, verbose_name='TOF LL'),
        ),
        migrations.AlterField(
            model_name='surface',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional information like purity, charge, serial number,...', max_length=5000),
        ),
    ]
