# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0002_auto_20190607_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='surface_material',
        ),
    ]
