# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0002_measurement_pusher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='pusher',
        ),
        migrations.AddField(
            model_name='measurement',
            name='acc_grid',
            field=models.FloatField(blank=True, default=-2000, null=True, verbose_name=b'Acceleration Grid'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def L'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_l_tof',
            field=models.FloatField(blank=True, default=-2000, null=True, verbose_name=b'Deflector L Tof'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_ou',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def O/U'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def R'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_r_tof',
            field=models.FloatField(blank=True, default=-2000, null=True, verbose_name=b'Deflector R Tof'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='drift',
            field=models.FloatField(blank=True, default=-2000, null=True, verbose_name=b'Drift Tube'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ion_block',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Ion Block'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='is_plate',
            field=models.FloatField(blank=True, null=True, verbose_name=b'IS front Plate'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='mcp',
            field=models.FloatField(blank=True, default=2300, null=True, verbose_name=b'MCP'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='post_acc',
            field=models.FloatField(blank=True, default=-4800, null=True, verbose_name=b'Post Accelaration'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pusher_is',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Pusher IS'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pusher_tof',
            field=models.FloatField(blank=True, default=400, null=True, verbose_name=b'Pusher Tof'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='reflectron',
            field=models.FloatField(blank=True, default=2000, null=True, verbose_name=b'Reflectron'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zb1l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'ZB1 L'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zb1r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'ZB1 R'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zb_2',
            field=models.FloatField(blank=True, null=True, verbose_name=b'ZB2'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zl_grid',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name=b'Zero Level Grid'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zyl1l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1 L'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zyl1r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1 R'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='zyl2',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl 2'),
        ),
    ]
