# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0003_remove_measurement_surface_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='surface_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surftof.Surface'),
        ),
    ]
