# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0003_auto_20160322_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='far_cup',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Trap Current'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fil_cur',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Filament Current'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='fil_vol',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Filament Voltage'),
        ),
    ]
