# Generated by Django 3.0.10 on 2020-10-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0004_auto_20200922_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='electron_impact_energy_source',
            field=models.FloatField(blank=True, null=True, verbose_name='EI IS [eV]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='electron_impact_energy_source_current',
            field=models.FloatField(blank=True, null=True, verbose_name='EI IS [mA]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='electron_impact_energy_tof',
            field=models.FloatField(blank=True, null=True, verbose_name='EI TOF [eV]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='electron_impact_energy_tof_current',
            field=models.FloatField(blank=True, null=True, verbose_name='EI TOF [mA]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='filament_is_current',
            field=models.FloatField(blank=True, null=True, verbose_name='IS [A]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='filament_is_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='IS [V]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='filament_tof_current',
            field=models.FloatField(blank=True, null=True, verbose_name='TOF [A]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='filament_tof_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='TOF [V]'),
        ),
    ]
