# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0004_auto_20160323_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='def_l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def2A L'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='def_r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def2B R'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zb1l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'ZB1A L'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zb1r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'ZB1B R'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zyl1l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1B L'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zyl1r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1A R'),
        ),
    ]
