# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0004_measurement_surface_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='gas_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gas_is', to='surftof.Gas'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gas_surf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gas_surf', to='surftof.Gas'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator', to='surftof.Operator'),
        ),
    ]
