# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0005_auto_20160330_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='def_ou',
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_o',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def1B U'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='def_u',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Def1A O'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='wehnelt',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Wehnelt'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zyl1l',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1A L'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='zyl1r',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Zyl1B R'),
        ),
    ]
