# Generated by Django 3.2.7 on 2021-09-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0006_journalentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='short_description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='journal/journalImage/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='journal/journalImage/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='journal/journalImage/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='journal/journalImage/'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surftof.measurement'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='journal/journalFiles/', verbose_name='File which can be downloaded'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal/journalImage/'),
        ),
    ]
