# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0006_auto_20190607_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialsettings',
            name='estimated_impact_energy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
