# Generated by Django 3.2.7 on 2021-09-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0007_auto_20210907_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='image',
            new_name='image1',
        ),
    ]
