# Generated by Django 3.2.9 on 2021-11-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0009_alter_journalentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='surface_temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Temperature (C)'),
        ),
    ]
