# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0009_auto_20190709_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='impact_energy',
            new_name='impact_energy_surface',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='evaluated_by',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='evaluation_comment',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_source_current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_source_voltage',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_tof_bottom_current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_tof_bottom_potential',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_tof_current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='filament_tof_voltage',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='file_evaluation',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='file_others',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='file_pressure_log',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='file_surface_current',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='file_tof',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='type_file_others',
        ),
        migrations.AddField(
            model_name='measurement',
            name='electron_impact_energy_source',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='electron_impact_energy_tof',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_source_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_source_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_tof_bottom_current',
            field=models.FloatField(blank=True, help_text=b'The current is produced by the filament top', null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_tof_bottom_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_tof_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='filament_tof_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='projectile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='Projectile',
        ),
    ]
