# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0010_auto_20190731_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsegAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1_ch00', models.CharField(blank=True, help_text=b'Use the exact names like in the potential settings', max_length=100)),
                ('m1_ch01', models.CharField(blank=True, max_length=100)),
                ('m1_ch02', models.CharField(blank=True, max_length=100)),
                ('m1_ch03', models.CharField(blank=True, max_length=100)),
                ('m1_ch04', models.CharField(blank=True, max_length=100)),
                ('m1_ch05', models.CharField(blank=True, max_length=100)),
                ('m1_ch06', models.CharField(blank=True, max_length=100)),
                ('m1_ch07', models.CharField(blank=True, max_length=100)),
                ('m2_ch00', models.CharField(blank=True, max_length=100)),
                ('m2_ch01', models.CharField(blank=True, max_length=100)),
                ('m2_ch02', models.CharField(blank=True, max_length=100)),
                ('m2_ch03', models.CharField(blank=True, max_length=100)),
                ('m2_ch04', models.CharField(blank=True, max_length=100)),
                ('m2_ch05', models.CharField(blank=True, max_length=100)),
                ('m2_ch06', models.CharField(blank=True, max_length=100)),
                ('m2_ch07', models.CharField(blank=True, max_length=100)),
                ('m2_ch08', models.CharField(blank=True, max_length=100)),
                ('m2_ch09', models.CharField(blank=True, max_length=100)),
                ('m2_ch10', models.CharField(blank=True, max_length=100)),
                ('m2_ch11', models.CharField(blank=True, max_length=100)),
                ('m3_ch00', models.CharField(blank=True, max_length=100)),
                ('m3_ch01', models.CharField(blank=True, max_length=100)),
                ('m3_ch02', models.CharField(blank=True, max_length=100)),
                ('m3_ch03', models.CharField(blank=True, max_length=100)),
                ('m3_ch04', models.CharField(blank=True, max_length=100)),
                ('m3_ch05', models.CharField(blank=True, max_length=100)),
                ('m3_ch06', models.CharField(blank=True, max_length=100)),
                ('m3_ch07', models.CharField(blank=True, max_length=100)),
                ('m3_ch08', models.CharField(blank=True, max_length=100)),
                ('m3_ch09', models.CharField(blank=True, max_length=100)),
                ('m3_ch10', models.CharField(blank=True, max_length=100)),
                ('m3_ch11', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ISEG assignments',
            },
        ),
    ]
