# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0011_isegassignments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialsettings',
            name='tdc_extraction_time',
        ),
        migrations.RemoveField(
            model_name='potentialsettings',
            name='tdc_frequency',
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='focus_1a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='focus_1b',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='source_cage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='source_ion_spacer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='source_pusher',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
