# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0012_auto_20190905_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassCalibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField(help_text=b'mass = a * (t - t0)^2')),
                ('to', models.FloatField()),
                ('potential_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surftof.PotentialSettings')),
            ],
        ),
    ]
