# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0013_masscalibration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='rating',
            field=models.IntegerField(choices=[(5, b'5 - Science'), (4, b'4 - Interesting'), (3, b'3 - Normal'), (2, b'2 - Not interesting'), (1, b'1 - Trash')], default=3),
        ),
    ]
