# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-09 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0015_countspermass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masscalibration',
            name='potential_settings',
        ),
        migrations.DeleteModel(
            name='MassCalibration',
        ),
    ]
