# Generated by Django 3.0.8 on 2020-07-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('vg', '0001_initial'), ('vg', '0002_measurement_fragment')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Turbopump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurbopumpStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vg.Turbopump')),
            ],
            options={
                'verbose_name_plural': 'Turbopump Status',
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('datafile', models.FileField(max_length=400, upload_to=b'vg/%Y/%m/%d/%H/%M/%S/')),
                ('scantype', models.CharField(choices=[(b'ES', b'Energyscan'), (b'MS', b'Massscan'), (b'MIKE', b'MIKE-Scan'), (b'CID', b'CID-Scan')], default=b'ES', max_length=20)),
                ('polarity', models.CharField(choices=[(b'NEG', b'Negative'), (b'POS', b'Positive')], default=b'NEG', max_length=3)),
                ('gatetime', models.FloatField(blank=True, null=True)),
                ('electron_energy', models.FloatField(blank=True, null=True, verbose_name=b'Electron Energy (for MS)')),
                ('substance', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('channeltron', models.FloatField(default=2.3, verbose_name=b'Channeltron (kV)')),
                ('ionblock_temperature', models.PositiveIntegerField(default=160)),
                ('trap_current', models.PositiveIntegerField(default=50)),
                ('filament_current', models.FloatField()),
                ('pressure_ionblock', models.CharField(default=b'1e-6', max_length=7, verbose_name=b'Pressure Ion Block (mbar)')),
                ('pressure_analyzer', models.CharField(default=b'1e-8', max_length=7, verbose_name=b'Pressure Analyzer (mbar)')),
                ('background_pressure', models.FloatField(blank=True, null=True, verbose_name=b'Background Pressure in IS (mbar)')),
                ('ion_repeller', models.FloatField(default=5.7)),
                ('focus_coarse_1', models.PositiveIntegerField()),
                ('focus_coarse_2', models.PositiveIntegerField()),
                ('focus_fine_1', models.FloatField(default=5.0)),
                ('focus_fine_2', models.FloatField(default=5.0)),
                ('deflector_1', models.FloatField()),
                ('deflector_2', models.FloatField()),
                ('ion_energy', models.FloatField()),
                ('y_focus', models.FloatField(verbose_name=b'Y-Focus')),
                ('x_deflect', models.FloatField(verbose_name=b'Y-Deflect')),
                ('z_deflect', models.FloatField(verbose_name=b'Z-Deflect')),
                ('curve_1', models.FloatField()),
                ('rotate_1', models.FloatField()),
                ('z_deflect_1', models.FloatField(verbose_name=b'Z-Deflect 1')),
                ('z_focus_1', models.FloatField(verbose_name=b'Z-Focus 1')),
                ('curve_2', models.FloatField()),
                ('rotate_2', models.FloatField()),
                ('z_deflect_2', models.FloatField(verbose_name=b'Z-Deflect 2')),
                ('z_focus_2', models.FloatField(verbose_name=b'Z-Focus 2')),
                ('comments', models.TextField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vg.Operator')),
                ('fragment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('comment', models.TextField()),
                ('attachment', models.FileField(blank=True, default=b'', upload_to=b'vg/techjournal/')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vg.Operator')),
            ],
            options={
                'ordering': ['-time'],
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('formula', models.CharField(blank=True, max_length=100, verbose_name=b'Calibration formula for copy-pasting')),
                ('logoutput', models.TextField(blank=True, verbose_name=b'Log output of fitlib')),
                ('p0', models.FloatField(blank=True)),
                ('p1', models.FloatField(blank=True)),
                ('p2', models.FloatField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('calibration_plot', models.FileField(blank=True, upload_to=b'vg/calibrations/')),
                ('cal_base_file_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_1', to='vg.Measurement', verbose_name=b'Basefile 1 used for this cal.')),
                ('cal_base_file_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_2', to='vg.Measurement', verbose_name=b'Basefile 2 used for this cal.')),
                ('cal_base_file_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_3', to='vg.Measurement', verbose_name=b'Basefile 3 used for this cal.')),
                ('cal_base_file_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calibration_cal_base_file_4', to='vg.Measurement', verbose_name=b'Basefile 4 used for this cal.')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
