# Generated by Django 3.2.9 on 2021-11-12 11:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width (mm)')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (mm)')),
                ('thickness', models.FloatField(blank=True, null=True, verbose_name='Thickness (mm)')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.CharField(choices=[('AFM', 'AFM'), ('STM', 'STM')], max_length=10)),
                ('rating', models.IntegerField(choices=[(5, '5 - Science'), (4, '4 - Interesting'), (3, '3 - Normal'), (2, '2 - Not interesting'), (1, '1 - Trash')], default=3)),
                ('tip', models.CharField(blank=True, max_length=500)),
                ('thickness', models.FloatField(blank=True, null=True, verbose_name='Thickness  (nm)')),
                ('sputter_time', models.FloatField(blank=True, null=True, verbose_name='Sputter Time (min)')),
                ('sputter_method', models.CharField(blank=True, choices=[('magnetronTi', 'Magnetron Titan'), ('magnetronAu', 'Magnetron Gold'), ('snowball', 'Snowball'), ('toffy', 'Toffy')], default='magnetronTi', max_length=20, null=True)),
                ('comment', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, default='Z:\\Experiments\\NanoParticles\\', help_text='Full path of the .nid file', max_length=500)),
                ('spectroscopy', models.BooleanField(default=False)),
                ('conductivity', models.BooleanField(default=False)),
                ('xps', models.BooleanField(default=False)),
                ('image_size', models.FloatField(blank=True, null=True, verbose_name='Image Size in µm')),
                ('coating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanoparticles.coating')),
                ('substrate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanoparticles.substrate')),
            ],
        ),
    ]
