# Generated by Django 3.2.9 on 2021-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeasurementData',
        ),
    ]
