# Generated by Django 3.2.9 on 2021-11-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0002_measurementdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurementdata',
            old_name='backward_amplitude',
            new_name='backward_amplitude_data',
        ),
        migrations.RenameField(
            model_name='measurementdata',
            old_name='backward_phase',
            new_name='backward_phase_data',
        ),
        migrations.RenameField(
            model_name='measurementdata',
            old_name='backward_z_axis',
            new_name='backward_z_axis_data',
        ),
        migrations.RenameField(
            model_name='measurementdata',
            old_name='forward_amplitude',
            new_name='forward_amplitude_data',
        ),
        migrations.RenameField(
            model_name='measurementdata',
            old_name='forward_phase',
            new_name='forward_phase_data',
        ),
        migrations.RenameField(
            model_name='measurementdata',
            old_name='forward_z_axis',
            new_name='forward_z_axis_data',
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='backward_amplitude_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='backward_phase_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='backward_z_axis_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='forward_amplitude_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='forward_phase_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurementdata',
            name='forward_z_axis_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
