# Generated by Django 3.2.9 on 2021-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanoparticles', '0003_auto_20211117_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
