# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def unpopulate_comment(apps, schema_editor):
         Measurements = apps.get_model('wippi', 'Measurement')
         for m in Measurements.objects.filter(substance_links__name = 'Unknown').all():
             m.substance_comments = ''
             m.save()

    def reverse_func(apps, schema_editor):
        pass

    dependencies = [
        ('wippi', '0007_auto_20160906_1547'),
    ]

    operations = [
    ]
