# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wippi', '0009_auto_20160906_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='substance_comments',
            new_name='substance_comment',
        ),
    ]
