# Generated by Django 3.0.8 on 2020-07-02 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('pulsetube', '0001_initial'), ('pulsetube', '0002_auto_20200617_1136'), ('pulsetube', '0003_auto_20200617_1138')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(blank=True, upload_to=b'pulsetube/dataFiles/')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_type', models.CharField(blank=True, choices=[(b'mass', b'Mass scan'), (b'energy', b'Energy scan'), (b'current', b'Current scan'), (b'temperature', b'Temperature scan')], max_length=20, null=True)),
                ('pressure_source', models.FloatField(blank=True, null=True)),
                ('pressure_sector', models.FloatField(blank=True, null=True)),
                ('he_temp', models.FloatField(verbose_name=b'He temperature')),
                ('he_pres', models.FloatField(verbose_name=b'He stagnation pressure')),
                ('ion_source_electron_energy', models.FloatField(verbose_name=b'Electron Energy [V]')),
                ('ion_source_filament_current', models.FloatField(verbose_name=b'Filament Current [A]')),
                ('ion_source_fc_current', models.FloatField(verbose_name=b'FC Current [uA]')),
                ('polarity', models.CharField(choices=[(b'pos', b'positive'), (b'neg', b'negative')], max_length=3)),
                ('channeltron_voltage', models.IntegerField(blank=True, null=True)),
                ('voltage_start', models.IntegerField(blank=True, null=True)),
                ('voltage_stop', models.IntegerField(blank=True, null=True)),
                ('voltage_step_size', models.IntegerField(blank=True, null=True)),
                ('time_per_step', models.FloatField(blank=True, null=True)),
                ('number_of_runs', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=1500)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator', to='pulsetube.Person')),
                ('operator_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_2', to='pulsetube.Person')),
            ],
        ),
    ]
