# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsetube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data_file',
            field=models.FileField(upload_to=b'pulsetube/dataFiles/'),
        ),
    ]
