# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsetube', '0002_auto_20200617_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='data_file',
            field=models.FileField(blank=True, upload_to=b'pulsetube/dataFiles/'),
        ),
    ]
