# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chemical_formula', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_tof', models.FileField(blank=True, upload_to=b'surftof/dataFilesTof/')),
                ('file_surface_current', models.FileField(blank=True, upload_to=b'surftof/dataFilesSurface/')),
                ('file_others', models.FileField(blank=True, upload_to=b'surftof/dataFilesOthers/')),
                ('type_file_others', models.CharField(blank=True, help_text=b"Specify, what will be found in 'file others'", max_length=100)),
                ('surface_material', models.CharField(blank=True, max_length=1500)),
                ('surface_temperature', models.FloatField(blank=True, null=True)),
                ('tof_ions', models.CharField(choices=[(b'NEG', b'Negative'), (b'POS', b'Positive')], default=b'POS', max_length=3)),
                ('impact_energy', models.FloatField(blank=True, null=True)),
                ('quadrupole_mass', models.FloatField(blank=True, null=True)),
                ('quadrupole_resolution', models.FloatField(blank=True, null=True)),
                ('pressure_ion_source_line', models.FloatField(blank=True, null=True)),
                ('pressure_ion_source_chamber', models.FloatField(blank=True, null=True)),
                ('pressure_surface_chamber', models.FloatField(blank=True, null=True)),
                ('pressure_tof_chamber', models.FloatField(blank=True, null=True)),
                ('filament_voltage', models.FloatField(blank=True, null=True)),
                ('filament_current', models.FloatField(blank=True, null=True)),
                ('filament_bottom_potential', models.FloatField(blank=True, null=True)),
                ('filament_bottom_current', models.FloatField(blank=True, help_text=b'The current is produced by the filament top', null=True)),
                ('file_evaluation', models.FileField(blank=True, upload_to=b'surftof/evaluation')),
                ('evaluation_comment', models.TextField(blank=True, max_length=5000)),
                ('comment', models.TextField(blank=True, max_length=5000)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluated_by', to='surftof.Operator')),
                ('gas_is', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_is', to='surftof.Gas')),
                ('gas_surf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_surf', to='surftof.Gas')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator', to='surftof.Operator')),
            ],
            options={
                'ordering': ['-time'],
                'get_latest_by': 'time',
            },
        ),
        migrations.CreateModel(
            name='Projectile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('polarity', models.CharField(choices=[(b'NEG', b'Negative'), (b'POS', b'Positive')], default=b'POS', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chemical_formula', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, help_text=b'Additional information like purity, charge, serial number,...', max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='slit_disc_angle',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Slit disc angle in degrees'),
        ),
        migrations.AddField(
            model_name='potentialsettings',
            name='surface_angle',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Surface angle in degrees'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='potential_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surftof.PotentialSettings'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='projectile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='surftof.Projectile'),
        ),
    ]
