# Generated by Django 3.0.8 on 2020-07-02 13:17

import cheminventory.validations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cheminventory', '0001_initial'), ('cheminventory', '0002_auto_20151006_0932'), ('cheminventory', '0003_auto_20151006_0946'), ('cheminventory', '0004_gascylinder_pressure'), ('cheminventory', '0005_gascylinder_quality'), ('cheminventory', '0006_auto_20160322_1543'), ('cheminventory', '0007_chemicalinstance_item_number'), ('cheminventory', '0008_auto_20190326_0947')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GHS_H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'GHS H',
                'verbose_name_plural': 'GHS H',
            },
        ),
        migrations.CreateModel(
            name='GHS_P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('text', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': 'GHS P',
                'verbose_name_plural': 'GHS P',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('office_phone', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('suitable_for', models.CharField(choices=[(b'FLUID', b'Fluid'), (b'GAS', b'Gas Phase'), (b'SOLID', b'Solid')], max_length=5)),
                ('toxic_or_health_hazard_necessary', models.BooleanField(default=False)),
                ('explosive_necessary', models.BooleanField(default=False)),
                ('oxidizing_necessary', models.BooleanField(default=False)),
                ('flammable_necessary', models.BooleanField(default=False)),
                ('irritant_necessary', models.BooleanField(default=False)),
                ('corrosive_necessary', models.BooleanField(default=False)),
                ('environmentally_damaging_necessary', models.BooleanField(default=False)),
                ('h2o_reactivity_necessary', models.BooleanField(default=False)),
                ('toxic_allowed', models.BooleanField(default=False)),
                ('explosive_allowed', models.BooleanField(default=False)),
                ('oxidizing_allowed', models.BooleanField(default=False)),
                ('flammable_allowed', models.BooleanField(default=False)),
                ('irritant_allowed', models.BooleanField(default=False)),
                ('corrosive_allowed', models.BooleanField(default=False)),
                ('health_hazard_allowed', models.BooleanField(default=False)),
                ('environmentally_damaging_allowed', models.BooleanField(default=False)),
                ('h2o_reactivity_allowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=6)),
                ('experiment', models.TextField(blank=True, max_length=1000)),
                ('responsible_persons', models.ManyToManyField(to='cheminventory.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, validators=[cheminventory.validations.validate_name], verbose_name=b'Common Name')),
                ('chemical_formula', models.CharField(blank=True, db_index=True, default=b'', max_length=40, validators=[cheminventory.validations.validate_chemical_formula], verbose_name=b'Chemical Formula')),
                ('inchi', models.CharField(blank=True, db_index=True, max_length=700, verbose_name=b'InChI')),
                ('inchikey', models.CharField(blank=True, db_index=True, max_length=27, verbose_name=b'InChI-Key')),
                ('cas', models.CharField(blank=True, max_length=12, validators=[cheminventory.validations.validate_CAS], verbose_name=b'CAS-Number')),
                ('csid', models.IntegerField(blank=True, null=True, verbose_name=b'CSID')),
                ('no_chemspider_sync', models.BooleanField(default=False, verbose_name=b'Do not sync with chemspider service')),
                ('state_of_matter', models.CharField(choices=[(b'FLUID', b'Fluid'), (b'GAS', b'Gas Phase'), (b'SOLID', b'Solid')], default=b'FLUID', max_length=5)),
                ('irritant', models.BooleanField()),
                ('toxic', models.BooleanField()),
                ('explosive', models.BooleanField()),
                ('oxidizing', models.BooleanField()),
                ('flammable', models.BooleanField()),
                ('health_hazard', models.BooleanField()),
                ('corrosive', models.BooleanField()),
                ('environmentally_damaging', models.BooleanField(verbose_name=b'Environ. dam.')),
                ('h2o_reactivity', models.BooleanField()),
                ('ghs_h', models.ManyToManyField(blank=True, to='cheminventory.GHS_H')),
                ('ghs_p', models.ManyToManyField(blank=True, to='cheminventory.GHS_P')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('csid', 'state_of_matter', 'irritant', 'toxic', 'explosive', 'oxidizing', 'flammable', 'health_hazard', 'corrosive', 'environmentally_damaging', 'h2o_reactivity'), ('cas', 'state_of_matter', 'irritant', 'toxic', 'explosive', 'oxidizing', 'flammable', 'health_hazard', 'corrosive', 'environmentally_damaging', 'h2o_reactivity'), ('inchikey', 'state_of_matter', 'irritant', 'toxic', 'explosive', 'oxidizing', 'flammable', 'health_hazard', 'corrosive', 'environmentally_damaging', 'h2o_reactivity')},
            },
        ),
        migrations.CreateModel(
            name='ChemicalInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('group', models.CharField(choices=[(b'DENIFL', b'Denifl'), (b'SCHEIER', b'Scheier')], default=b'DENIFL', max_length=7, null=True)),
                ('last_used', models.DateField(blank=True, null=True)),
                ('last_user', models.CharField(blank=True, max_length=100, null=True)),
                ('cylinder_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name=b'Number of gas cylinder in wiki')),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemical_instance', to='cheminventory.Chemical')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheminventory.StorageLocation')),
                ('usage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cheminventory.UsageLocation')),
                ('item_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'order_with_respect_to': 'chemical',
            },
        ),
        migrations.CreateModel(
            name='GasCylinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_number', models.IntegerField(unique=True, verbose_name=b'Number of gas cylinder')),
                ('company', models.CharField(blank=True, max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('group', models.CharField(choices=[(b'DENIFL', b'Denifl'), (b'SCHEIER', b'Scheier')], default=b'SCHEIER', max_length=7, null=True)),
                ('comments', models.TextField(blank=True, max_length=1000)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_cylinder', to='cheminventory.Chemical')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheminventory.StorageLocation')),
                ('pressure', models.FloatField(default=200)),
                ('quality', models.FloatField(default=5.0)),
            ],
        ),
        migrations.CreateModel(
            name='GasCylinderUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('gas_cylinder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheminventory.GasCylinder')),
                ('usage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheminventory.UsageLocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cheminventory.Person')),
            ],
        ),
    ]
