# Generated by Django 3.0.8 on 2020-09-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0002_auto_20200703_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountsPerMass',
        ),
    ]
