# Generated by Django 3.0.10 on 2020-09-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0003_delete_countspermass'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='electron_impact_energy_source_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='electron_impact_energy_tof_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filament_is_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filament_is_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filament_tof_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='filament_tof_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas_setpoint_is',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='gas_setpoint_surf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
