# Generated by Django 3.2.7 on 2021-09-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surftof', '0007_auto_20210910_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='image',
            new_name='image1',
        ),
    ]
