# Generated by Django 3.2.7 on 2021-09-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0004_auto_20210910_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='attachment',
            new_name='file',
        ),
    ]
