# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0006_auto_20160322_1543'),
        ('clustof', '0005_vacuumstatus_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='chem_pu1_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chem_pu1_gas', to='cheminventory.Chemical', verbose_name=b'Chemical PU1 Gas'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='chem_pu1_oven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chem_pu1_oven', to='cheminventory.Chemical', verbose_name=b'Chemical PU1 Oven'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='chem_pu2_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chem_pu2_gas', to='cheminventory.Chemical', verbose_name=b'Chemical PU2 Gas'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='chem_pu2_oven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chem_pu2_oven', to='cheminventory.Chemical', verbose_name=b'Chemical PU2 Oven'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='substance',
            field=models.TextField(max_length=1500, verbose_name=b'Comment'),
        ),
    ]
