# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheminventory', '0006_auto_20160322_1543'),
        ('clustof', '0006_auto_20160718_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_inlet_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_inlet_gas', to='cheminventory.Chemical', verbose_name=b'Ion Source Inlet Gas'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='operator2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op2', to='clustof.Operator'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='operator3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op3', to='clustof.Operator'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op1', to='clustof.Operator'),
        ),
    ]
