# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0008_auto_20160913_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='extraction_1_left',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='extraction_1_right',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='extraction_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
