# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0009_auto_20170808_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='laser_timing',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
