# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0010_measurement_laser_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='laser_timing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
