# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0011_auto_20180412_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='laser_power_file',
            field=models.FileField(blank=True, upload_to=b'clustof/powerfiles/', verbose_name=b'Laser Power Measurement File'),
        ),
    ]
