# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0012_measurement_laser_power_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='scantype',
            field=models.CharField(choices=[(b'ES', b'Energyscan'), (b'MS', b'Mass Spectrum'), (b'TS', b'Temperature-Scan'), (b'PS', b'Pressure-Scan'), (b'LS', b'Laser-Scan'), (b'OLD', b'Unknown (Old File)')], default=b'MS', max_length=20),
        ),
    ]
