# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-09 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0013_auto_20190109_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='cluster_size_distribution',
            field=models.FileField(blank=True, null=True, upload_to=b'clustof/clusterSizeDistribution/'),
        ),
    ]
