# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0015_auto_20200520_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='lis_deflector_y',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Deflector Y'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lis_deflector_z',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Deflector Z'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lis_electron_energy',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Electron energy'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lis_filament_current',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Filament current'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lis_ion_block',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Ion block'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='lis_trap_current',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Trap current'),
        ),
    ]
