from django import forms

CURRENT_CHOICES = (
    ('file', 'By current file, saved to the corresponding ID on bigshare'),
    ('value', 'Set a value below'),
    ('fixed', 'Fixed value: 1e-9'),
    ('none', 'No normalization')
)


class CountsPerMassForm(forms.Form):
    id_list = forms.CharField(max_length=500, help_text="Use numbers, separated by comma only - (i.e. 9-11,13)")
    current_normalization = forms.ChoiceField(choices=CURRENT_CHOICES)
    current_normalization_value = forms.FloatField(
        required=False, help_text="Set only, if you selected 'Set a value below' in the field before.")
    mass_1_mass_nominal = forms.FloatField()
    mass_1_mass_min = forms.FloatField()
    mass_1_mass_max = forms.FloatField()
    mass_1_zero_min = forms.FloatField()
    mass_1_zero_max = forms.FloatField()
    mass_2_mass_nominal = forms.FloatField(required=False)
    mass_2_mass_min = forms.FloatField(required=False)
    mass_2_mass_max = forms.FloatField(required=False)
    mass_2_zero_min = forms.FloatField(required=False)
    mass_2_zero_max = forms.FloatField(required=False)
    mass_3_mass_nominal = forms.FloatField(required=False)
    mass_3_mass_min = forms.FloatField(required=False)
    mass_3_mass_max = forms.FloatField(required=False)
    mass_3_zero_min = forms.FloatField(required=False)
    mass_3_zero_max = forms.FloatField(required=False)
    mass_4_mass_nominal = forms.FloatField(required=False)
    mass_4_mass_min = forms.FloatField(required=False)
    mass_4_mass_max = forms.FloatField(required=False)
    mass_4_zero_min = forms.FloatField(required=False)
    mass_4_zero_max = forms.FloatField(required=False)
    mass_5_mass_nominal = forms.FloatField(required=False)
    mass_5_mass_min = forms.FloatField(required=False)
    mass_5_mass_max = forms.FloatField(required=False)
    mass_5_zero_min = forms.FloatField(required=False)
    mass_5_zero_max = forms.FloatField(required=False)
    mass_6_mass_nominal = forms.FloatField(required=False)
    mass_6_mass_min = forms.FloatField(required=False)
    mass_6_mass_max = forms.FloatField(required=False)
    mass_6_zero_min = forms.FloatField(required=False)
    mass_6_zero_max = forms.FloatField(required=False)
    mass_7_mass_nominal = forms.FloatField(required=False)
    mass_7_mass_min = forms.FloatField(required=False)
    mass_7_mass_max = forms.FloatField(required=False)
    mass_7_zero_min = forms.FloatField(required=False)
    mass_7_zero_max = forms.FloatField(required=False)
    mass_8_mass_nominal = forms.FloatField(required=False)
    mass_8_mass_min = forms.FloatField(required=False)
    mass_8_mass_max = forms.FloatField(required=False)
    mass_8_zero_min = forms.FloatField(required=False)
    mass_8_zero_max = forms.FloatField(required=False)
    mass_9_mass_nominal = forms.FloatField(required=False)
    mass_9_mass_min = forms.FloatField(required=False)
    mass_9_mass_max = forms.FloatField(required=False)
    mass_9_zero_min = forms.FloatField(required=False)
    mass_9_zero_max = forms.FloatField(required=False)
