# Generated by Django 3.2.12 on 2022-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labbook_experiment', models.CharField(choices=[['clustof', 'ClustTof'], ['toffy', 'Toffy'], ['toffy2', 'Toffy2'], ['surftof', 'SurfTof']], max_length=10, unique=True)),
                ('experiment_id_mscp', models.IntegerField(help_text='Go to https://ideadb.uibk.ac.at/mscp/admin/node/experiment/ and use that ID here.')),
            ],
        ),
        migrations.CreateModel(
            name='MscpToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
