# Generated by Django 3.2.3 on 2021-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustof', '0002_auto_20200703_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='pressure_pu3',
            field=models.FloatField(default=1e-06, verbose_name='Pressure PU3'),
        ),
    ]
