# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_bwd_down',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_bwd_up',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_fwd_down',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_fwd_up',
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux1 Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_enable',
            field=models.NullBooleanField(verbose_name='Aux1 Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux1 Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 V Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux1 V Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_enable',
            field=models.NullBooleanField(verbose_name='Aux1 V Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux1 V Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 V Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_v_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 V Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 Z Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux1 Z Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_enable',
            field=models.NullBooleanField(verbose_name='Aux1 Z Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux1 Z Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 Z Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux1_z_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux1 Z Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux2 Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_enable',
            field=models.NullBooleanField(verbose_name='Aux2 Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux2 Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_t_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux2 t Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_t_enable',
            field=models.NullBooleanField(verbose_name='Aux2 t Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_t_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux2 t Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_t_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 t Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_t_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 t Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 V Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux2 V Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_enable',
            field=models.NullBooleanField(verbose_name='Aux2 V Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux2 V Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 V Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_v_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 V Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 Z Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Aux2 Z Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_enable',
            field=models.NullBooleanField(verbose_name='Aux2 Z Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_enable_storing',
            field=models.NullBooleanField(verbose_name='Aux2 Z Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 Z Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='aux2_z_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Aux2 Z Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock1_enable',
            field=models.NullBooleanField(verbose_name='Clock1 Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock1_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock1 Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock1_samples',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock1 Samples'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock2_enable',
            field=models.NullBooleanField(verbose_name='Clock2 Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock2_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock2 Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock2_samples',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock2 Samples'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock3_enable',
            field=models.NullBooleanField(verbose_name='Clock3 Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock3_period',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock3 Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='clock3_samples',
            field=models.FloatField(blank=True, null=True, verbose_name='Clock3 Samples'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_aab_mux_0',
            field=models.FloatField(blank=True, null=True, verbose_name='CRTCService AAB Mux 0'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_aab_mux_1',
            field=models.FloatField(blank=True, null=True, verbose_name='CRTCService AAB Mux 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_aab_mux_2',
            field=models.FloatField(blank=True, null=True, verbose_name='CRTCService AAB Mux 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_aab_mux_3',
            field=models.FloatField(blank=True, null=True, verbose_name='CRTCService AAB Mux 3'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_enable_pfu_filter',
            field=models.NullBooleanField(verbose_name='CRTCService Enable PFU Filter'),
        ),
        migrations.AddField(
            model_name='image',
            name='crtcservice_pfu_z_gain',
            field=models.FloatField(blank=True, null=True, verbose_name='CRTCService PFU Z Gain'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_aux1_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Aux1 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_aux2_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Aux2 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_aux1_in',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Lp Aux1 In'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_aux1_in_aa',
            field=models.NullBooleanField(verbose_name='DRBService Lp Aux1 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_aux2_in',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Lp Aux2 In'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_aux2_in_aa',
            field=models.NullBooleanField(verbose_name='DRBService Lp Aux2 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_z_ext',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Lp Z Ext'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_lp_z_out',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService Lp Z Out'),
        ),
        migrations.AddField(
            model_name='image',
            name='drbservice_vcal_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='DRBService VCal In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_alternate_preamp_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='GapVoltageControl Alternate Preamp Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_alternate_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='GapVoltageControl Alternate Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_const_voltage',
            field=models.NullBooleanField(verbose_name='GapVoltageControl Const Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_enable_alternate_preamp_range',
            field=models.NullBooleanField(verbose_name='GapVoltageControl Enable Alternate Preamp Range'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_enable_alternate_voltage',
            field=models.NullBooleanField(verbose_name='GapVoltageControl Enable Alternate Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_preamp_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='GapVoltageControl Preamp Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_tip_cond_enable_feedback_loop',
            field=models.NullBooleanField(verbose_name='GapVoltageControl Tip Cond Enable Feedback Loop'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_tip_cond_pulse_preamp_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='GapVoltageControl Tip Cond Pulse Preamp Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_tip_cond_pulse_time',
            field=models.FloatField(blank=True, null=True, verbose_name='GapVoltageControl Tip Cond Pulse Time'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_tip_cond_pulse_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='GapVoltageControl Tip Cond Pulse Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='gapvoltagecontrol_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='GapVoltageControl Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_auto_oversampling',
            field=models.NullBooleanField(verbose_name='I Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_enable',
            field=models.NullBooleanField(verbose_name='I Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_enable_storing',
            field=models.NullBooleanField(verbose_name='I Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='I Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='I Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_reg_auto_oversampling',
            field=models.NullBooleanField(verbose_name='I Reg Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_reg_enable',
            field=models.NullBooleanField(verbose_name='I Reg Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_reg_enable_storing',
            field=models.NullBooleanField(verbose_name='I Reg Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_reg_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='I Reg Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_reg_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='I Reg Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_t_auto_oversampling',
            field=models.NullBooleanField(verbose_name='I t Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_t_enable',
            field=models.NullBooleanField(verbose_name='I t Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_t_enable_storing',
            field=models.NullBooleanField(verbose_name='I t Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_t_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='I t Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_t_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='I t Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='I V Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_auto_oversampling',
            field=models.NullBooleanField(verbose_name='I V Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_enable',
            field=models.NullBooleanField(verbose_name='I V Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_enable_storing',
            field=models.NullBooleanField(verbose_name='I V Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='I V Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_v_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='I V Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_auto_flush_period',
            field=models.FloatField(blank=True, null=True, verbose_name='I Z Auto Flush Period'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_auto_oversampling',
            field=models.NullBooleanField(verbose_name='I Z Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_enable',
            field=models.NullBooleanField(verbose_name='I Z Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_enable_storing',
            field=models.NullBooleanField(verbose_name='I Z Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='I Z Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='i_z_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='I Z Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_adc_read_mode_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator ADC Read Mode 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_adc_read_mode_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator ADC Read Mode 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_algorithm_characteristics_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Algorithm Characteristics 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_algorithm_characteristics_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Algorithm Characteristics 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_line_weighting',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Line Weighting'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_1_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 1 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_1_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 1 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_1_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 1 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_1_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 1 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_2_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 2 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_2_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 2 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_2_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 2 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_loop_gain_2_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Loop Gain 2 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_setpoint_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Setpoint 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_alternate_setpoint_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Alternate Setpoint 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_mode_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Mode 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_mode_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Mode 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_post_ramp_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Post Ramp Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_pre_ramp_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Pre Ramp Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_ramp_speed_high_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Ramp Speed High Range'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_ramp_speed_low_range',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Ramp Speed Low Range'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_retraction_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Retraction Speed'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_auto_approach_timeout',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Auto Approach Timeout'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_const_setpoint',
            field=models.NullBooleanField(verbose_name='Regulator Const Setpoint'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_delta_f_min_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Delta f Min 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_delta_f_min_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Delta f Min 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_line_weighting',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Line Weighting'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_d',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 1 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_i',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 1 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_k',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 1 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_p',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 1 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_d',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 2 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_i',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 2 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_k',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 2 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_p',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Loop Gain 2 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_setpoint_1',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Setpoint 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_alternate_setpoint_2',
            field=models.NullBooleanField(verbose_name='Regulator Enable Alternate Setpoint 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_z_offset_slew_rate',
            field=models.NullBooleanField(verbose_name='Regulator Enable Z Offset Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_z_offset_special_slew_rate',
            field=models.NullBooleanField(verbose_name='Regulator Enable Z Offset Special Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_z_ramp_gap_voltage',
            field=models.NullBooleanField(verbose_name='Regulator Enable Z Ramp Gap Voltage'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_enable_z_ramp_slew_rate',
            field=models.NullBooleanField(verbose_name='Regulator Enable Z Ramp Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_feedback_loop_characteristic_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Feedback Loop Characteristic 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_feedback_loop_characteristic_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Feedback Loop Characteristic 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_feedback_loop_enabled',
            field=models.NullBooleanField(verbose_name='Regulator Feedback Loop Enabled'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_line_weighting',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Line Weighting'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_1_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 1 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_1_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 1 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_1_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 1 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_1_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 1 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_2_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 2 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_2_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 2 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_2_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 2 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_loop_gain_2_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Loop Gain 2 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_preamp_range_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regulator Preamp Range 1 (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_preamp_range_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regulator Preamp Range 2 (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_retraction_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Retraction Speed'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_run_frequency',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Run Frequency'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_setpoint_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Setpoint 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_setpoint_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Setpoint 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_setpoint_limit_absolute_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Setpoint Limit Absolute 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_setpoint_limit_absolute_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Setpoint Limit Absolute 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_sign_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Sign 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_sign_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Sign 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_line_weighting',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Line Weighting'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_1_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 1 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_1_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 1 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_1_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 1 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_1_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 1 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_2_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 2 D'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_2_i',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 2 I'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_2_k',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 2 K'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_loop_gain_2_p',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Loop Gain 2 P'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_preamp_range_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regulator Special Preamp Range 1 (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_preamp_range_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Regulator Special Preamp Range 2 (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_setpoint_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Setpoint 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_special_setpoint_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Special Setpoint 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset_special',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset Special'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset_special_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset Special Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_offset_special_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Offset Special Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_ramp',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Ramp'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_ramp_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Ramp Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='regulator_z_ramp_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Regulator Z Ramp Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_aux1_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spectroscopy Alternate Aux1 Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_aux2_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spectroscopy Alternate Aux2 Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t1_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T1 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t1_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T1 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t2_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T2 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t2_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T2 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t3_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T3 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t3_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T3 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t4_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T4 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_delay_t4_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Delay T4 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_1_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 1 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_1_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 1 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_1_start',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 1 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_2_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 2 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_2_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 2 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_device_2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Device 2 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation VExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation VExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vmod_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation VMod T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vmod_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation VMod T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_zext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation ZExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_modulation_zext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Alternate Modulation ZExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_alternate_spectroscopy_mode',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Alternate Spectroscopy Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_aux1_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spectroscopy Aux1 Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_aux2_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spectroscopy Aux2 Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_correction_strategy',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Correction Strategy'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t1_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T1 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t1_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T1 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t2_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T2 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t2_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T2 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t3_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T3 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t3_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T3 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t4_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T4 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_delay_t4_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Delay T4 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 Points'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_ramp_step_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 Ramp Step Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_repetitions',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 Repetitions'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_1_start',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 1 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_change_negative',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Change Negative'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_change_positive',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Change Positive'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_end',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_offset',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Offset'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_offset_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Offset Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_points',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Points'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_ramp_step_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Ramp Step Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_repetitions',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Repetitions'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_device_2_start',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Device 2 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_disable_feedback_loop',
            field=models.NullBooleanField(verbose_name='Spectroscopy Disable Feedback Loop'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_aux1_range',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Aux1 Range'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_aux2_range',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Aux2 Range'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t1_1',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T1 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t1_2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T1 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t2_1',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T2 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t2_2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T2 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t3_1',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T3 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t3_2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T3 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t4_1',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T4 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t4_2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Delay T4 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_end',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 1 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 1 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_start',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 1 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_end',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 2 End'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 2 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_start',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Device 2 Start'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation VExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation VExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vmod_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation VMod T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vmod_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation VMod T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_zext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation ZExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_zext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Modulation ZExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_alternate_spectroscopy_mode',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Alternate Spectroscopy Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_1_ramp_reversal',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 1 Ramp Reversal'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_1_ramp_step_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 1 Ramp Step Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_1_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 1 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_2_ramp_reversal',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 2 Ramp Reversal'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_2_ramp_step_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 2 Ramp Step Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_device_2_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Device 2 Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_gap_preset',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Gap Preset'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_gap_voltage_preset_slew_rate',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Gap Voltage Preset Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_mode_locks',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Mode Locks'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_modulation',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Modulation'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_enable_status_signals',
            field=models.NullBooleanField(verbose_name='Spectroscopy Enable Status Signals'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_preset_feedback_post_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Gap Preset Feedback Post Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_preset_feedback_pre_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Gap Preset Feedback Pre Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_preset_mode',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Gap Preset Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_voltage_preset',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Gap Voltage Preset'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_voltage_preset_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='Spectroscopy Gap Voltage Preset Range (Unit: --)'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_gap_voltage_preset_slew_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Gap Voltage Preset Slew Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_maximum_points_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Maximum Points 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_maximum_points_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Maximum Points 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_vext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation VExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_vext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation VExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_vmod_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation VMod T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_vmod_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation VMod T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_zext_t1t2',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation ZExt T1T2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_modulation_zext_t2t3',
            field=models.NullBooleanField(verbose_name='Spectroscopy Modulation ZExt T2T3'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_pause_conduct_mode',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Pause Conduct Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_raster_time_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Raster Time 1'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_raster_time_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Raster Time 2'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_reenable_feedback_loop',
            field=models.NullBooleanField(verbose_name='Spectroscopy Reenable Feedback Loop'),
        ),
        migrations.AddField(
            model_name='image',
            name='spectroscopy_spectroscopy_mode',
            field=models.FloatField(blank=True, null=True, verbose_name='Spectroscopy Spectroscopy Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_it_select',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService IT Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_lp_it_image_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService Lp IT Image AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_lp_it_regulator',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService Lp IT Regulator'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_lp_it_regulator_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService Lp IT Regulator AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_lp_vgap_out_rg',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService Lp VGap Out Rg'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_vcal_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService VCal In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_vgap_int_ext_select',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService VGap Int Ext Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_vgap_out_mod_select',
            field=models.NullBooleanField(verbose_name='STMSCBService VGap Out Mod Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_vgap_out_select',
            field=models.FloatField(blank=True, null=True, verbose_name='STMSCBService VGap Out Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='stmscbservice_vgap_select',
            field=models.NullBooleanField(verbose_name='STMSCBService VGap Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_adc1_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService ADC1 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_adc2_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService ADC2 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_adc3_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService ADC3 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_adc4_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService ADC4 In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_dac1_cal_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService DAC1 Cal In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_dac1_out_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService DAC1 Out Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_dac2_cal_in_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService DAC2 Cal In Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_dac2_out_select',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService DAC2 Out Select'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_adc1_in_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp ADC1 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_adc2_in_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp ADC2 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_adc3_in_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp ADC3 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_adc4_in_aa',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp ADC4 In AA'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_dac1_out_rg',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp DAC1 Out Rg'),
        ),
        migrations.AddField(
            model_name='image',
            name='uscbservice_lp_dac2_out_rg',
            field=models.FloatField(blank=True, null=True, verbose_name='USCBService Lp DAC2 Out Rg'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_angle',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Angle'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_auto_disable_scan',
            field=models.NullBooleanField(verbose_name='XYScanner Auto Disable Scan'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_drift_compensation_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Drift Compensation Ratio'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_drift_offset_elimination_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Drift Offset Elimination Rate'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_enable_automatic_drift_compensation',
            field=models.NullBooleanField(verbose_name='XYScanner Enable Automatic Drift Compensation'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_enable_drift_compensation',
            field=models.NullBooleanField(verbose_name='XYScanner Enable Drift Compensation'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_enable_scan',
            field=models.NullBooleanField(verbose_name='XYScanner Enable Scan'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_enable_subgrid',
            field=models.NullBooleanField(verbose_name='XYScanner Enable Subgrid'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_exact_match',
            field=models.NullBooleanField(verbose_name='XYScanner Exact Match'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_height',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Height'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_line_end_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Line End Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_line_start_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Line Start Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_lines',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Lines'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_move_raster_time',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Move Raster Time'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_move_raster_time_constrained',
            field=models.NullBooleanField(verbose_name='XYScanner Move Raster Time Constrained'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_points',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Points'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_points_lines_constrained',
            field=models.NullBooleanField(verbose_name='XYScanner Points Lines Constrained'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_raster_time',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Raster Time'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_relocation_step_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Relocation Step Limit'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_relocation_time_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Relocation Time Limit'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_scan_constraint',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Scan Constraint'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_speed_adaptation',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Speed Adaptation'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_subgrid_constrained',
            field=models.NullBooleanField(verbose_name='XYScanner Subgrid Constrained'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_subgrid_match_mode',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Subgrid Match Mode'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_subgrid_x',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Subgrid X'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_subgrid_y',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Subgrid Y'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_width',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Width (Volts)'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_width_height_constrained',
            field=models.NullBooleanField(verbose_name='XYScanner Width Height Constrained'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_x_drift',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner X Drift'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_x_offset',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner X Offset'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_x_retrace',
            field=models.NullBooleanField(verbose_name='XYScanner X Retrace'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_y_drift',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Y Drift'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_y_offset',
            field=models.FloatField(blank=True, null=True, verbose_name='XYScanner Y Offset'),
        ),
        migrations.AddField(
            model_name='image',
            name='xyscanner_y_retrace',
            field=models.NullBooleanField(verbose_name='XYScanner Y Retrace'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_enable',
            field=models.NullBooleanField(verbose_name='Z Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_enable_storing',
            field=models.NullBooleanField(verbose_name='Z Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Z Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Z Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_t_auto_oversampling',
            field=models.NullBooleanField(verbose_name='Z t Auto Oversampling'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_t_enable',
            field=models.NullBooleanField(verbose_name='Z t Enable'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_t_enable_storing',
            field=models.NullBooleanField(verbose_name='Z t Enable Storing'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_t_initial_delay',
            field=models.FloatField(blank=True, null=True, verbose_name='Z t Initial Delay'),
        ),
        migrations.AddField(
            model_name='image',
            name='z_t_oversampling_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='Z t Oversampling Factor'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
