# Generated by Django 3.1.3 on 2020-11-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm', '0002_auto_20200703_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aux1_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux1 Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_enable',
            field=models.BooleanField(null=True, verbose_name='Aux1 Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux1 Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_v_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux1 V Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_v_enable',
            field=models.BooleanField(null=True, verbose_name='Aux1 V Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_v_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux1 V Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_z_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux1 Z Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_z_enable',
            field=models.BooleanField(null=True, verbose_name='Aux1 Z Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux1_z_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux1 Z Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux2 Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_enable',
            field=models.BooleanField(null=True, verbose_name='Aux2 Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux2 Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_t_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux2 t Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_t_enable',
            field=models.BooleanField(null=True, verbose_name='Aux2 t Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_t_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux2 t Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_v_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux2 V Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_v_enable',
            field=models.BooleanField(null=True, verbose_name='Aux2 V Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_v_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux2 V Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_z_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Aux2 Z Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_z_enable',
            field=models.BooleanField(null=True, verbose_name='Aux2 Z Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aux2_z_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Aux2 Z Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='clock1_enable',
            field=models.BooleanField(null=True, verbose_name='Clock1 Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='clock2_enable',
            field=models.BooleanField(null=True, verbose_name='Clock2 Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='clock3_enable',
            field=models.BooleanField(null=True, verbose_name='Clock3 Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='crtcservice_enable_pfu_filter',
            field=models.BooleanField(null=True, verbose_name='CRTCService Enable PFU Filter'),
        ),
        migrations.AlterField(
            model_name='image',
            name='drbservice_lp_aux1_in_aa',
            field=models.BooleanField(null=True, verbose_name='DRBService Lp Aux1 In AA'),
        ),
        migrations.AlterField(
            model_name='image',
            name='drbservice_lp_aux2_in_aa',
            field=models.BooleanField(null=True, verbose_name='DRBService Lp Aux2 In AA'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gapvoltagecontrol_const_voltage',
            field=models.BooleanField(null=True, verbose_name='GapVoltageControl Const Voltage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gapvoltagecontrol_enable_alternate_preamp_range',
            field=models.BooleanField(null=True, verbose_name='GapVoltageControl Enable Alternate Preamp Range'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gapvoltagecontrol_enable_alternate_voltage',
            field=models.BooleanField(null=True, verbose_name='GapVoltageControl Enable Alternate Voltage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gapvoltagecontrol_tip_cond_enable_feedback_loop',
            field=models.BooleanField(null=True, verbose_name='GapVoltageControl Tip Cond Enable Feedback Loop'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='I Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_enable',
            field=models.BooleanField(null=True, verbose_name='I Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_enable_storing',
            field=models.BooleanField(null=True, verbose_name='I Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_reg_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='I Reg Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_reg_enable',
            field=models.BooleanField(null=True, verbose_name='I Reg Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_reg_enable_storing',
            field=models.BooleanField(null=True, verbose_name='I Reg Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_t_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='I t Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_t_enable',
            field=models.BooleanField(null=True, verbose_name='I t Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_t_enable_storing',
            field=models.BooleanField(null=True, verbose_name='I t Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_v_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='I V Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_v_enable',
            field=models.BooleanField(null=True, verbose_name='I V Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_v_enable_storing',
            field=models.BooleanField(null=True, verbose_name='I V Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_z_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='I Z Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_z_enable',
            field=models.BooleanField(null=True, verbose_name='I Z Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='i_z_enable_storing',
            field=models.BooleanField(null=True, verbose_name='I Z Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_const_setpoint',
            field=models.BooleanField(null=True, verbose_name='Regulator Const Setpoint'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_line_weighting',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Line Weighting'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_d',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 1 D'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_i',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 1 I'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_k',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 1 K'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_1_p',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 1 P'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_d',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 2 D'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_i',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 2 I'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_k',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 2 K'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_loop_gain_2_p',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Loop Gain 2 P'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_setpoint_1',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Setpoint 1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_alternate_setpoint_2',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Alternate Setpoint 2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_z_offset_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Z Offset Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_z_offset_special_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Z Offset Special Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_z_ramp_gap_voltage',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Z Ramp Gap Voltage'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_enable_z_ramp_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Regulator Enable Z Ramp Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='regulator_feedback_loop_enabled',
            field=models.BooleanField(null=True, verbose_name='Regulator Feedback Loop Enabled'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation VExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation VExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vmod_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation VMod T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_vmod_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation VMod T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_zext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation ZExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_alternate_modulation_zext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Alternate Modulation ZExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_disable_feedback_loop',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Disable Feedback Loop'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_aux1_range',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Aux1 Range'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_aux2_range',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Aux2 Range'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t1_1',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T1 1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t1_2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T1 2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t2_1',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T2 1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t2_2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T2 2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t3_1',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T3 1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t3_2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T3 2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t4_1',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T4 1'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_delay_t4_2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Delay T4 2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_end',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 1 End'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 1 Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_1_start',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 1 Start'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_end',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 2 End'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 2 Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_device_2_start',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Device 2 Start'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation VExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation VExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vmod_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation VMod T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_vmod_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation VMod T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_zext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation ZExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_modulation_zext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Modulation ZExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_alternate_spectroscopy_mode',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Alternate Spectroscopy Mode'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_1_ramp_reversal',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 1 Ramp Reversal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_1_ramp_step_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 1 Ramp Step Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_1_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 1 Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_2_ramp_reversal',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 2 Ramp Reversal'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_2_ramp_step_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 2 Ramp Step Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_device_2_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Device 2 Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_gap_preset',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Gap Preset'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_gap_voltage_preset_slew_rate',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Gap Voltage Preset Slew Rate'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_mode_locks',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Mode Locks'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_modulation',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Modulation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_enable_status_signals',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Enable Status Signals'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_vext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation VExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_vext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation VExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_vmod_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation VMod T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_vmod_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation VMod T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_zext_t1t2',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation ZExt T1T2'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_modulation_zext_t2t3',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Modulation ZExt T2T3'),
        ),
        migrations.AlterField(
            model_name='image',
            name='spectroscopy_reenable_feedback_loop',
            field=models.BooleanField(null=True, verbose_name='Spectroscopy Reenable Feedback Loop'),
        ),
        migrations.AlterField(
            model_name='image',
            name='stmscbservice_vgap_out_mod_select',
            field=models.BooleanField(null=True, verbose_name='STMSCBService VGap Out Mod Select'),
        ),
        migrations.AlterField(
            model_name='image',
            name='stmscbservice_vgap_select',
            field=models.BooleanField(null=True, verbose_name='STMSCBService VGap Select'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_auto_disable_scan',
            field=models.BooleanField(null=True, verbose_name='XYScanner Auto Disable Scan'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_enable_automatic_drift_compensation',
            field=models.BooleanField(null=True, verbose_name='XYScanner Enable Automatic Drift Compensation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_enable_drift_compensation',
            field=models.BooleanField(null=True, verbose_name='XYScanner Enable Drift Compensation'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_enable_scan',
            field=models.BooleanField(null=True, verbose_name='XYScanner Enable Scan'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_enable_subgrid',
            field=models.BooleanField(null=True, verbose_name='XYScanner Enable Subgrid'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_exact_match',
            field=models.BooleanField(null=True, verbose_name='XYScanner Exact Match'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_move_raster_time_constrained',
            field=models.BooleanField(null=True, verbose_name='XYScanner Move Raster Time Constrained'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_points_lines_constrained',
            field=models.BooleanField(null=True, verbose_name='XYScanner Points Lines Constrained'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_subgrid_constrained',
            field=models.BooleanField(null=True, verbose_name='XYScanner Subgrid Constrained'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_width_height_constrained',
            field=models.BooleanField(null=True, verbose_name='XYScanner Width Height Constrained'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_x_retrace',
            field=models.BooleanField(null=True, verbose_name='XYScanner X Retrace'),
        ),
        migrations.AlterField(
            model_name='image',
            name='xyscanner_y_retrace',
            field=models.BooleanField(null=True, verbose_name='XYScanner Y Retrace'),
        ),
        migrations.AlterField(
            model_name='image',
            name='z_enable',
            field=models.BooleanField(null=True, verbose_name='Z Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='z_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Z Enable Storing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='z_t_auto_oversampling',
            field=models.BooleanField(null=True, verbose_name='Z t Auto Oversampling'),
        ),
        migrations.AlterField(
            model_name='image',
            name='z_t_enable',
            field=models.BooleanField(null=True, verbose_name='Z t Enable'),
        ),
        migrations.AlterField(
            model_name='image',
            name='z_t_enable_storing',
            field=models.BooleanField(null=True, verbose_name='Z t Enable Storing'),
        ),
    ]
