# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm', '0002_auto_20180410_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='stm/preview_images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('I', 'I'), ('V', 'V')], default='I', max_length=2),
            preserve_default=False,
        ),
    ]
