# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stm', '0003_auto_20180412_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('I', 'I'), ('V', 'V'), ('Z', 'Z')], max_length=2),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
