# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stm', '0004_auto_20180419_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stm.Operator'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
