INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H300', 'Fatal if swallowed');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H301', 'Toxic if swallowed');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H302', 'Harmful if swallowed');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H303', 'May be harmful if swallowed');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H304', 'May be fatal if swallowed and enters airways');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H305', 'May be harmful if swallowed and enters airways');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H310', 'Fatal in contact with skin');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H311', 'Toxic in contact with skin');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H312', 'Harmful in contact with skin');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H313', 'May be harmful in contact with skin');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H314', 'Causes severe skin burns and eye damage');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H315', 'Causes skin irritation');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H316', 'Causes mild skin irritation');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H317', 'May cause an allergic skin reaction');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H318', 'Causes serious eye damage');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H319', 'Causes serious eye irritation');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H320', 'Causes eye irritation');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H330', 'Fatal if inhaled');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H331', 'Toxic if inhaled');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H332', 'Harmful if inhaled');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H333', 'May be harmful if inhaled');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H334', 'May cause allergy or asthma symptoms or breathing difficulties if inhaled');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H335', 'May cause respiratory irritation');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H336', 'May cause drowsiness or dizziness');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H340', 'May cause genetic defects');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H341', 'Suspected of causing genetic defects');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H350', 'May cause cancer');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H351', 'Suspected of causing cancer');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H360', 'May damage fertility or the unborn child');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H361', 'Suspected of damaging fertility or the unborn child');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H361d', 'Suspected of damaging the unborn child');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H362', 'May cause harm to breast-fed children');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H370', 'Causes damage to organs');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H371', 'May cause damage to organs');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H372', 'Causes damage to organs through prolonged or repeated exposure');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H373', 'May cause damage to organs through prolonged or repeated exposure');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H400', 'Very toxic to aquatic life');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H401', 'Toxic to aquatic life');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H402', 'Harmful to aquatic life');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H410', 'Very toxic to aquatic life with long lasting effects');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H411', 'Toxic to aquatic life with long lasting effects');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H412', 'Harmful to aquatic life with long lasting effects');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H413', 'May cause long lasting harmful effects to aquatic life');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H420', 'Harms public health and the environment by destroying ozone in the upper atmosphere');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H200', 'Unstable explosive');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H201', 'Explosive; mass explosion hazard');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H202', 'Explosive; severe projection hazard');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H203', 'Explosive; fire, blast or projection hazard');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H204', 'Fire or projection hazard');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H205', 'May mass explode in fire');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H220', 'Extremely flammable gas');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H221', 'Flammable gas');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H222', 'Extremely flammable aerosol');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H223', 'Flammable aerosol');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H224', 'Extremely flammable liquid and vapour');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H225', 'Highly flammable liquid and vapour');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H226', 'Flammable liquid and vapour');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H227', 'Combustible liquid');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H228', 'Flammable solid');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H229', 'Pressurized container: may burst if heated');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H230', 'May react explosively even in the absence of air');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H231', 'May react explosively even in the absence of air at elevated pressure and/or temperature');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H240', 'Heating may cause an explosion');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H241', 'Heating may cause a fire or explosion');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H242', 'Heating may cause a fire');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H250', 'Catches fire spontaneously if exposed to air');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H251', 'Self-heating; may catch fire');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H252', 'Self-heating in large quantities; may catch fire');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H260', 'In contact with water releases flammable gases which may ignite spontaneously');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H261', 'In contact with water releases flammable gas');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H270', 'May cause or intensify fire; oxidizer');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H271', 'May cause fire or explosion; strong oxidizer');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H272', 'May intensify fire; oxidizer');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H280', 'Contains gas under pressure; may explode if heated');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H281', 'Contains refrigerated gas; may cause cryogenic burns or injury');
INSERT INTO cheminventory_ghs_h (number, text) VALUES ('H290', 'May be corrosive to metals');
