INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P101', 'If medical advice is needed, have product container or label at hand');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P102', 'Keep out of reach of children');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P103', 'Read label before use');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P201', 'Obtain special instructions before use');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P202', 'Do not handle until all safety precautions have been read and understood');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P210', 'Keep away from heat/sparks/open flames/hot surfaces – No smoking');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P211', 'Do not spray on an open flame or other ignition source');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P220', 'Keep/Store away from clothing/…/combustible materials');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P221', 'Take any precaution to avoid mixing with combustibles');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P222', 'Do not allow contact with air');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P223', 'Keep away from any possible contact with water, because of violent reaction and possible flash fire');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P230', 'Keep wetted with …');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P231', 'Handle under inert gas');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P232', 'Protect from moisture');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P233', 'Keep container tightly closed');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P234', 'Keep only in original container');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P235', 'Keep cool');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P240', 'Ground/bond container and receiving equipment');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P241', 'Use explosion-proof electrical/ventilating/light/…/equipment');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P242', 'Use only non-sparking tools');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P243', 'Take precautionary measures against static discharge');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P244', 'Keep reduction valves free from grease and oil');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P250', 'Do not subject to grinding/shock/…/friction');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P251', 'Pressurized container – Do not pierce or burn, even after use');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P260', 'Do not breathe dust/fume/gas/mist/vapours/spray');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P261', 'Avoid breathing dust/fume/gas/mist/vapours/spray');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P262', 'Do not get in eyes, on skin, or on clothing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P263', 'Avoid contact during pregnancy/while nursing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P264', 'Wash … thoroughly after handling');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P270', 'Do not eat, drink or smoke when using this product');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P271', 'Use only outdoors or in a well-ventilated area');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P272', 'Contaminated work clothing should not be allowed out of the workplace');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P273', 'Avoid release to the environment');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P280', 'Wear protective gloves/protective clothing/eye protection/face protection');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P281', 'Use personal protective equipment as required');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P282', 'Wear cold insulating gloves/face shield/eye protection');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P283', 'Wear fire/flame resistant/retardant clothing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P284', 'Wear respiratory protection');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P285', 'In case of inadequate ventilation wear respiratory protection');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P301', 'IF SWALLOWED:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P302', 'IF ON SKIN:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P303', 'IF ON SKIN (or hair):');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P304', 'IF INHALED:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P305', 'IF IN EYES:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P306', 'IF ON CLOTHING:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P307', 'IF exposed:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P308', 'IF exposed or concerned:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P309', 'IF exposed or you feel unwell:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P310', 'Immediately call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P311', 'Call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P312', 'Call a POISON CENTER or doctor/physician if you feel unwell');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P313', 'Get medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P314', 'Get Medical advice/attention if you feel unwell');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P315', 'Get immediate medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P320', 'Specific treatment is urgent (see … on this label)');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P321', 'Specific treatment (see … on this label)');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P322', 'Specific measures (see … on this label)');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P330', 'Rinse mouth');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P331', 'Do NOT induce vomiting');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P332', 'If skin irritation occurs:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P333', 'If skin irritation or a rash occurs:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P334', 'Immerse in cool water/wrap in wet bandages');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P335', 'Brush off loose particles from skin');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P336', 'Thaw frosted parts with lukewarm water. Do not rub affected areas');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P337', 'If eye irritation persists:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P338', 'Remove contact lenses if present and easy to do. continue rinsing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P340', 'Remove victim to fresh air and keep at rest in a position comfortable for breathing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P341', 'If breathing is difficult, remove victim to fresh air and keep at rest in a position comfortable for breathing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P342', 'If experiencing respiratory symptoms:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P350', 'Gently wash with plenty of soap and water');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P351', 'Rinse cautiously with water for several minutes');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P352', 'Wash with soap and water');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P353', 'Rinse skin with water/shower');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P360', 'Rinse immediately contaminated clothing and skin with plenty of water before removing clothes');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P361', 'Remove/Take off immediately all contaminated clothing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P362', 'Take off contaminated clothing and wash before reuse');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P363', 'Wash contaminated clothing before reuse');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P370', 'In case of fire:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P371', 'In case of major fire and large quantities:');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P372', 'Explosion risk in case of fire');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P373', 'DO NOT fight fire when fire reaches explosives');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P374', 'Fight fire with normal precautions from a reasonable distance');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P375', 'Fight fire remotely due to the risk of explosion');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P376', 'Stop leak if safe to do so');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P377', 'Leaking gas fire – do not extinguish unless leak can be stopped safely');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P378', 'Use … for extinction');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P380', 'Evacuate area');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P381', 'Eliminate all ignition sources if safe to do so');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P391', 'Collect spillage');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P401', 'Store …');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P402', 'Store in a dry place');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P403', 'Store in a well ventilated place');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P404', 'Store in a closed container');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P405', 'Store locked up');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P406', 'Store in a corrosive resistant/… container with a resistant inner liner');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P407', 'Maintain air gap between stacks/pallets');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P410', 'Protect from sunlight');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P411', 'Store at temperatures not exceeding … °C/… °F');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P412', 'Do not expose to temperatures exceeding 50 °C/122 °F');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P413', 'Store bulk masses greater than … kg/… lbs at temperatures not exceeding … °C/… °F');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P420', 'Store away from other materials');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P422', 'Store contents under …');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P501', 'Dispose of contents/container to …');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P231+232', 'Handle under inert gas. Protect from moisture');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P235+410', 'Keep cool. Protect from sunlight');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P301+310', 'IF SWALLOWED: Immediately call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P301+312', 'IF SWALLOWED: Call a POISON CENTER or doctor/physician if you feel unwell');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P301+330+331', 'IF SWALLOWED: Rinse mouth. Do NOT induce vomiting');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P302+334', 'IF ON SKIN: Immerse in cool water/wrap in wet bandages');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P302+350', 'IF ON SKIN: Gently wash with plenty of soap and water');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P302+352', 'IF ON SKIN: Wash with soap and water');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P303+361+353', 'IF ON SKIN (or hair): Remove/Take off immediately all contaminated clothing. Rinse skin with water/shower');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P304+312', 'IF INHALED: Call a POISON CENTER or doctor/physician if you feel unwell');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P304+340', 'IF INHALED: Remove victim to fresh air and keep at rest in a position comfortable for breathing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P304+341', 'IF INHALED: If breathing is difficult, remove victim to fresh air and keep at rest in a position comfortable for breathing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P305+351+338', 'IF IN EYES: Rinse cautiously with water for several minutes. Remove contact lenses if present and easy to do – continue rinsing');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P306+360', 'IF ON CLOTHING: Rinse immediately contaminated clothing and skin with plenty of water before removing clothes');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P307+311', 'IF exposed: Call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P308+313', 'IF exposed or concerned: Get medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P309+311', 'IF exposed or you feel unwell: Call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P332+313', 'If skin irritation occurs: Get medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P333+313', 'If skin irritation or a rash occurs: Get medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P335+334', 'Brush off loose particles from skin. Immerse in cool water/wrap in wet bandages');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P337+313', 'If eye irritation persists get medical advice/attention');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P342+311', 'If experiencing respiratory symptoms: Call a POISON CENTER or doctor/physician');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P370+376', 'In case of fire: Stop leak if safe to do so');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P370+378', 'In case of fire: Use … for extinction');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P370+380', 'In case of fire: Evacuate area');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P370+380+375', 'In case of fire: Evacuate area. Fight fire remotely due to the risk of explosion');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P371+380+375', 'In case of major fire and large quantities: Evacuate area. Fight fire remotely due to the risk of explosion');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P402+404', 'Store in a dry place. Store in a closed container');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P403+233', 'Store in a well ventilated place. Keep container tightly closed');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P403+235', 'Store in a well ventilated place. Keep cool');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P410+403', 'Protect from sunlight. Store in a well ventilated place');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P410+412', 'Protect from sunlight. Do not expose to temperatures exceeding 50 °C/122 °F');
INSERT INTO cheminventory_ghs_p (number, text) VALUES ('P411+235', 'Store at temperatures not exceeding … °C/… °F. Keep cool');
