# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-06 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('toffy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='bender_inner_voltage',
            new_name='bender_float_voltage',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='bender_outer_voltage',
            new_name='bender_deflect_voltage',
        ),
    ]
