# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-06 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0002_rename_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='bender_deflect_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Deflect voltage [V]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='bender_float_voltage',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Float voltage [V]'),
        ),
    ]
