# Generated by Django 3.2.9 on 2021-12-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0006_alter_journalentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oventype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='oventype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='toffy.oventype'),
            preserve_default=False,
        ),
    ]
