# Generated by Django 3.2.9 on 2022-01-04 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0006_alter_journalentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oventype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='measurement',
            name='coll_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Coll bronki [a.U.]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='evap_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Evap bronki [a.U.]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pickup_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Pickup bronki [a.U.]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pickup_pressure',
            field=models.FloatField(blank=True, default=1e-05, null=True, verbose_name='Pickup pressure [mbar]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='quad_pressure',
            field=models.FloatField(blank=True, default=1e-06, null=True, verbose_name='Quad pressure [mbar]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='collision_pressure',
            field=models.FloatField(blank=True, default=1e-05, null=True, verbose_name='Pressure [mbar]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='evaporation_pressure',
            field=models.FloatField(blank=True, default=0.0001, null=True, verbose_name='Pressure [mbar]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='oventype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='toffy.oventype'),
            preserve_default=False,
        ),
    ]
