# Generated by Django 3.2.9 on 2022-01-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0007_auto_20220104_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='collision_gas',
            field=models.CharField(blank=True, default='Argon', max_length=100, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='evaporation_gas',
            field=models.CharField(blank=True, default='Helium', max_length=100, verbose_name='Gas'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='oven_type',
            field=models.CharField(blank=True, choices=[('organic', 'Organic'), ('metal', 'Metal'), ('external', 'External'), ('description', 'See description')], max_length=20, null=True, verbose_name='Oven type'),
        ),
    ]
