# Generated by Django 3.2.9 on 2021-12-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0007_auto_20211230_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='oventype',
            field=models.ForeignKey(default='Organic', on_delete=django.db.models.deletion.PROTECT, to='toffy.oventype'),
        ),
    ]
