# Generated by Django 3.2.9 on 2021-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0008_alter_measurement_oventype'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='pickup_pressure',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name='Pickup pressure [bar]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='quad_pressure',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name='Quad pressure [bar]'),
        ),
    ]
