# Generated by Django 3.2.9 on 2022-01-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toffy', '0009_auto_20211230_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='coll_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Coll bronki [a.U.]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='evap_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Evap bronki [a.U.]'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pickup_bronk',
            field=models.FloatField(blank=True, default=99, null=True, verbose_name='Pickup bronki [a.U.]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pickup_pressure',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name='Pickup pressure [mbar]'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='quad_pressure',
            field=models.FloatField(blank=True, default=20, null=True, verbose_name='Quad pressure [mbar]'),
        ),
    ]
